-- +goose Up
INSERT INTO cities (code, name, name_en, full_name, full_name_en) VALUES
('ha-noi', 'Hà Nội', 'Hanoi', 'Thành phố Hà Nội', 'Hanoi City'),
('cao-bang', 'Cao Bằng', 'Cao Bang', 'Tỉnh Cao Bằng', 'Cao Bang Province'),
('tuyen-quang', 'Tuyên Quang', 'Tuyen Quang', 'Tỉnh Tuyên Quang', 'Tuyen Quang Province'),
('dien-bien', 'Điện Biên', 'Dien Bien', 'Tỉnh Điện Biên', 'Dien Bien Province'),
('lai-chau', 'Lai Châu', 'Lai Chau', 'Tỉnh Lai Châu', 'Lai Chau Province'),
('son-la', 'Sơn La', 'Son La', 'Tỉnh Sơn La', 'Son La Province'),
('lao-cai', 'Lào Cai', 'Lao Cai', 'Tỉnh Lào Cai', 'Lao Cai Province'),
('thai-nguyen', 'Thái Nguyên', 'Thai Nguyen', 'Tỉnh Thái Nguyên', 'Thai Nguyen Province'),
('lang-son', 'Lạng Sơn', 'Lang Son', 'Tỉnh Lạng Sơn', 'Lang Son Province'),
('quang-ninh', 'Quảng Ninh', 'Quang Ninh', 'Tỉnh Quảng Ninh', 'Quang Ninh Province'),
('bac-ninh', 'Bắc Ninh', 'Bac Ninh', 'Tỉnh Bắc Ninh', 'Bac Ninh Province'),
('phu-tho', 'Phú Thọ', 'Phu Tho', 'Tỉnh Phú Thọ', 'Phu Tho Province'),
('hai-phong', 'Hải Phòng', 'Haiphong', 'Thành phố Hải Phòng', 'Haiphong City'),
('hung-yen', 'Hưng Yên', 'Hung Yen', 'Tỉnh Hưng Yên', 'Hung Yen Province'),
('ninh-binh', 'Ninh Bình', 'Ninh Binh', 'Tỉnh Ninh Bình', 'Ninh Binh Province'),
('thanh-hoa', 'Thanh Hoá', 'Thanh Hoa', 'Tỉnh Thanh Hoá', 'Thanh Hoa Province'),
('nghe-an', 'Nghệ An', 'Nghe An', 'Tỉnh Nghệ An', 'Nghe An Province'),
('ha-tinh', 'Hà Tĩnh', 'Ha Tinh', 'Tỉnh Hà Tĩnh', 'Ha Tinh Province'),
('quang-tri', 'Quảng Trị', 'Quang Tri', 'Tỉnh Quảng Trị', 'Quang Tri Province'),
('hue', 'Huế', 'Hue', 'Thành phố Huế', 'Hue City'),
('da-nang', 'Đà Nẵng', 'Da Nang', 'Thành phố Đà Nẵng', 'Da Nang City'),
('quang-ngai', 'Quảng Ngãi', 'Quang Ngai', 'Tỉnh Quảng Ngãi', 'Quang Ngai Province'),
('gia-lai', 'Gia Lai', 'Gia Lai', 'Tỉnh Gia Lai', 'Gia Lai Province'),
('khanh-hoa', 'Khánh Hoà', 'Khanh Hoa', 'Tỉnh Khánh Hoà', 'Khanh Hoa Province'),
('dak-lak', 'Đắk Lắk', 'Dak Lak', 'Tỉnh Đắk Lắk', 'Dak Lak Province'),
('lam-dong', 'Lâm Đồng', 'Lam Dong', 'Tỉnh Lâm Đồng', 'Lam Dong Province'),
('dong-nai', 'Đồng Nai', 'Dong Nai', 'Thành phố Đồng Nai', 'Dong Nai City'),
('ho-chi-minh', 'Hồ Chí Minh', 'Ho Chi Minh', 'Thành phố Hồ Chí Minh', 'Ho Chi Minh City'),
('tay-ninh', 'Tây Ninh', 'Tay Ninh', 'Tỉnh Tây Ninh', 'Tay Ninh Province'),
('dong-thap', 'Đồng Tháp', 'Dong Thap', 'Tỉnh Đồng Tháp', 'Dong Thap Province'),
('vinh-long', 'Vĩnh Long', 'Vinh Long', 'Tỉnh Vĩnh Long', 'Vinh Long Province'),
('an-giang', 'An Giang', 'An Giang', 'Tỉnh An Giang', 'An Giang Province'),
('can-tho', 'Cần Thơ', 'Can Tho', 'Thành phố Cần Thơ', 'Can Tho City'),
('ca-mau', 'Cà Mau', 'Ca Mau', 'Tỉnh Cà Mau', 'Ca Mau Province');

-- +goose Down
