post:
  tags:
    - Admin Organizer Applications
  operationId: approveAdminOrganizerApplication
  x-ogen-operation-group: OrganizerApplications
  summary: Approve an organizer application
  security:
    - adminAuth: []
  parameters:
    - name: organizerApplicationId
      in: path
      required: true
      schema:
        $ref: ../components/schemas/UUID.yaml
  responses:
    '200':
      description: Successful response.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/OrganizerApplication.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    default:
      $ref: ../components/responses/Default.yaml
