// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAccountByFirebaseUID = `-- name: GetAccountByFirebaseUID :one
SELECT id, full_name, email, avatar, status, suspended_at, created_at, updated_at, firebase_uid, phone, phone_changed_at
FROM accounts
WHERE firebase_uid = $1::text
`

func (q *Queries) GetAccountByFirebaseUID(ctx context.Context, firebaseUid string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByFirebaseUID, firebaseUid)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUID,
		&i.Phone,
		&i.PhoneChangedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, full_name, email, avatar, status, suspended_at, created_at, updated_at, firebase_uid, phone, phone_changed_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUID,
		&i.Phone,
		&i.PhoneChangedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (firebase_uid, full_name, email, avatar, phone)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (firebase_uid) DO UPDATE
    SET updated_at = accounts.updated_at
RETURNING id, full_name, email, avatar, status, suspended_at, created_at, updated_at, firebase_uid, phone, phone_changed_at
`

type InsertAccountParams struct {
	FirebaseUID string
	FullName    string
	Email       string
	Avatar      string
	Phone       string
}

// A repeat is the same identity finishing a setup that was interrupted, so the
// row it already holds is the answer. DO NOTHING would return no row at all,
// hence a write that changes nothing.
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.FirebaseUID,
		arg.FullName,
		arg.Email,
		arg.Avatar,
		arg.Phone,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUID,
		&i.Phone,
		&i.PhoneChangedAt,
	)
	return i, err
}
