// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategories = `-- name: GetCategories :many
SELECT id, name, slug, icon, display_order, status, created_at, updated_at
FROM categories
WHERE status = 'active'
ORDER BY display_order
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.DisplayOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :execrows
INSERT INTO categories (name, slug, icon, display_order)
VALUES ($1, $2, $3, $4)
`

type InsertCategoryParams struct {
	Name         string
	Slug         string
	Icon         pgtype.Text
	DisplayOrder int16
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCategory,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.DisplayOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
