// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: city.sql

package database

import (
	"context"
)

const getCities = `-- name: GetCities :many
SELECT code, name, name_en, full_name, full_name_en, status
FROM cities
WHERE status = 'active'
`

func (q *Queries) GetCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, getCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.FullName,
			&i.FullNameEn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
