// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID
	FullName    string
	Email       string
	Avatar      string
	Status      string
	SuspendedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Asset struct {
	ID          uuid.UUID
	StorageKey  string
	Status      string
	ContentType string
	SizeBytes   pgtype.Int8
	Checksum    pgtype.Text
	CreatedAt   time.Time
	CommittedAt *time.Time
}

type Category struct {
	ID           int16
	Name         string
	Slug         string
	Icon         pgtype.Text
	DisplayOrder int16
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type City struct {
	Code       string
	Name       string
	NameEn     pgtype.Text
	FullName   string
	FullNameEn pgtype.Text
	Status     string
}

type Event struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	CategoryID  pgtype.Int2
	Name        string
	Slug        string
	Description string
	Image       string
	Status      string
	IsListed    bool
	IsFeatured  bool
	PublishedAt *time.Time
	ClosedAt    *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Occurrence struct {
	ID                 uuid.UUID
	EventID            uuid.UUID
	Name               string
	StartTime          time.Time
	EndTime            time.Time
	VenueName          string
	VenueAddress       string
	VenueCityCode      pgtype.Text
	Status             string
	WaitingRoomEnabled bool
	CanceledAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Order struct {
	ID            uuid.UUID
	CustomerID    uuid.UUID
	OccurrenceID  uuid.UUID
	TotalAmount   int64
	Status        string
	HoldExpiresAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type OrderItem struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	TicketCategoryID uuid.UUID
	Quantity         int32
	UnitPrice        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Organizer struct {
	ID            uuid.UUID
	Name          string
	Description   string
	OrganizerType string
	Logo          string
	Email         string
	Phone         string
	PublicContact []byte
	Status        string
	ActivatedAt   *time.Time
	SuspendedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type OrganizerApplication struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	Status      string
	ReviewNote  string
	ReviewedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrganizerMember struct {
	OrganizerID uuid.UUID
	AccountID   uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlatformStaff struct {
	AccountID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SalePhase struct {
	ID                uuid.UUID
	OccurrenceID      uuid.UUID
	Name              string
	StartTime         time.Time
	EndTime           time.Time
	MaxBuyPerCustomer int32
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SalePhaseCategory struct {
	SalePhaseID      uuid.UUID
	TicketCategoryID uuid.UUID
}

type Ticket struct {
	ID               uuid.UUID
	OrderItemID      uuid.UUID
	EventID          uuid.UUID
	OccurrenceID     uuid.UUID
	TicketCategoryID uuid.UUID
	QrCode           string
	Status           string
	IssuedAt         time.Time
	UsedAt           *time.Time
	UpdatedAt        time.Time
}

type TicketCategory struct {
	ID                uuid.UUID
	OccurrenceID      uuid.UUID
	Name              string
	Zone              string
	Price             int64
	Quantity          int32
	Priority          int32
	Metadata          []byte
	MaxBuyPerCustomer int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
