// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_staff.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlatformStaffByAccountID = `-- name: GetPlatformStaffByAccountID :one
SELECT account_id, created_at, updated_at, role, granted_by
FROM platform_staff
WHERE account_id = $1
`

func (q *Queries) GetPlatformStaffByAccountID(ctx context.Context, accountID uuid.UUID) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, getPlatformStaffByAccountID, accountID)
	var i PlatformStaff
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.GrantedBy,
	)
	return i, err
}

const listPlatformStaff = `-- name: ListPlatformStaff :many
SELECT
    s.account_id, s.created_at, s.updated_at, s.role, s.granted_by,
    a.firebase_uid,
    a.full_name,
    a.email,
    a.avatar
FROM platform_staff AS s
INNER JOIN accounts AS a ON s.account_id = a.id
ORDER BY s.created_at
`

type ListPlatformStaffRow struct {
	AccountID   uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Role        string
	GrantedBy   *uuid.UUID
	FirebaseUID string
	FullName    string
	Email       string
	Avatar      string
}

func (q *Queries) ListPlatformStaff(ctx context.Context) ([]ListPlatformStaffRow, error) {
	rows, err := q.db.Query(ctx, listPlatformStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformStaffRow
	for rows.Next() {
		var i ListPlatformStaffRow
		if err := rows.Scan(
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.GrantedBy,
			&i.FirebaseUID,
			&i.FullName,
			&i.Email,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlatformStaff = `-- name: UpsertPlatformStaff :one
INSERT INTO platform_staff (account_id, role, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE
    SET
        role = excluded.role,
        updated_at = now()
RETURNING account_id, created_at, updated_at, role, granted_by
`

type UpsertPlatformStaffParams struct {
	AccountID uuid.UUID
	Role      string
	GrantedBy *uuid.UUID
}

func (q *Queries) UpsertPlatformStaff(ctx context.Context, arg UpsertPlatformStaffParams) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, upsertPlatformStaff, arg.AccountID, arg.Role, arg.GrantedBy)
	var i PlatformStaff
	err := row.Scan(
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.GrantedBy,
	)
	return i, err
}
