// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateCategory(ctx context.Context, id int64) (Category, error)
	DeactivateCategory(ctx context.Context, id int64) (Category, error)
	GetAccountByFirebaseUID(ctx context.Context, firebaseUid string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetCategories(ctx context.Context) ([]Category, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetPlatformStaffByAccountID(ctx context.Context, accountID uuid.UUID) (PlatformStaff, error)
	// A repeat is the same identity finishing a setup that was interrupted, so the
	// row it already holds is the answer. DO NOTHING would return no row at all,
	// hence a write that changes nothing.
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error)
	ListPlatformStaff(ctx context.Context) ([]ListPlatformStaffRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpsertPlatformStaff(ctx context.Context, arg UpsertPlatformStaffParams) (PlatformStaff, error)
}

var _ Querier = (*Queries)(nil)
