version: "2"

linters:
  # errcheck, govet, ineffassign, staticcheck, unused.
  default: standard
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - misspell
    - noctx
  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - gotick
  exclusions:
    generated: strict
