type: object
properties:
  id:
    $ref: ./UUID.yaml
  status:
    $ref: ./OrganizerApplicationStatus.yaml
  reviewNote:
    type: string
  reviewedAt:
    type: string
    format: date-time
  organizer:
    $ref: ./Organizer.yaml
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
required:
  - id
  - status
  - reviewNote
  - organizer
  - createdAt
  - updatedAt
