type: object
properties:
  id:
    $ref: ./UUID.yaml
  organizerId:
    $ref: ./UUID.yaml
  version:
    $ref: ./OrganizerApplicationVersion.yaml
  kind:
    $ref: ./OrganizerApplicationKind.yaml
  status:
    $ref: ./OrganizerApplicationStatus.yaml
  profile:
    $ref: ./OrganizerProfile.yaml
  reviewNote:
    type: string
  reviewedAt:
    type: string
    format: date-time
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
required:
  - id
  - version
  - kind
  - status
  - profile
  - reviewNote
  - createdAt
  - updatedAt
