// Code generated by ogen, DO NOT EDIT.
package oas

type ActivateAdminCategoryRes interface {
	activateAdminCategoryRes()
}

type ActivateAdminCityRes interface {
	activateAdminCityRes()
}

type ActivateAdminOrganizerRes interface {
	activateAdminOrganizerRes()
}

type AddOrgMemberRes interface {
	addOrgMemberRes()
}

type ApproveAdminOrganizerApplicationRes interface {
	approveAdminOrganizerApplicationRes()
}

type CancelOrgOccurrenceRes interface {
	cancelOrgOccurrenceRes()
}

type CancelOrgSalePhaseRes interface {
	cancelOrgSalePhaseRes()
}

type CloseOrgEventRes interface {
	closeOrgEventRes()
}

type CreateAdminCategoryRes interface {
	createAdminCategoryRes()
}

type CreateAdminCityRes interface {
	createAdminCityRes()
}

type CreateMyOrderRes interface {
	createMyOrderRes()
}

type CreateMyOrganizerApplicationRes interface {
	createMyOrganizerApplicationRes()
}

type CreateMyProfileRes interface {
	createMyProfileRes()
}

type CreateOrgEventRes interface {
	createOrgEventRes()
}

type CreateOrgOccurrenceRes interface {
	createOrgOccurrenceRes()
}

type CreateOrgSalePhaseRes interface {
	createOrgSalePhaseRes()
}

type CreateOrgTicketCategoryRes interface {
	createOrgTicketCategoryRes()
}

type DeactivateAdminCategoryRes interface {
	deactivateAdminCategoryRes()
}

type DeactivateAdminCityRes interface {
	deactivateAdminCityRes()
}

type EndOrgSalePhaseRes interface {
	endOrgSalePhaseRes()
}

type GetAdminCategoryRes interface {
	getAdminCategoryRes()
}

type GetAdminCityRes interface {
	getAdminCityRes()
}

type GetMyOrderRes interface {
	getMyOrderRes()
}

type GetMyOrganizerApplicationRes interface {
	getMyOrganizerApplicationRes()
}

type GetMyProfileRes interface {
	getMyProfileRes()
}

type GetMyTicketRes interface {
	getMyTicketRes()
}

type GetOrgEventRes interface {
	getOrgEventRes()
}

type GetOrgOccurrenceRes interface {
	getOrgOccurrenceRes()
}

type GetOrgSalePhaseRes interface {
	getOrgSalePhaseRes()
}

type GetOrgTicketCategoryRes interface {
	getOrgTicketCategoryRes()
}

type GetPublicEventRes interface {
	getPublicEventRes()
}

type GetPublicOrganizerRes interface {
	getPublicOrganizerRes()
}

type ListAdminCategoriesRes interface {
	listAdminCategoriesRes()
}

type ListAdminCitiesRes interface {
	listAdminCitiesRes()
}

type ListAdminOrganizerApplicationsRes interface {
	listAdminOrganizerApplicationsRes()
}

type ListAdminOrganizersRes interface {
	listAdminOrganizersRes()
}

type ListAdminStaffRes interface {
	listAdminStaffRes()
}

type ListMyOrdersRes interface {
	listMyOrdersRes()
}

type ListMyOrganizerApplicationsRes interface {
	listMyOrganizerApplicationsRes()
}

type ListMyTicketsRes interface {
	listMyTicketsRes()
}

type ListOrgEventsRes interface {
	listOrgEventsRes()
}

type ListOrgMembersRes interface {
	listOrgMembersRes()
}

type ListOrgOccurrencesRes interface {
	listOrgOccurrencesRes()
}

type ListOrgSalePhasesRes interface {
	listOrgSalePhasesRes()
}

type ListOrgTicketCategoriesRes interface {
	listOrgTicketCategoriesRes()
}

type ListPublicCategoriesRes interface {
	listPublicCategoriesRes()
}

type ListPublicCitiesRes interface {
	listPublicCitiesRes()
}

type ListPublicEventOccurrencesRes interface {
	listPublicEventOccurrencesRes()
}

type ListPublicEventsRes interface {
	listPublicEventsRes()
}

type ListPublicFeaturedEventsRes interface {
	listPublicFeaturedEventsRes()
}

type ListPublicOrganizersRes interface {
	listPublicOrganizersRes()
}

type ListPublicRelatedEventsRes interface {
	listPublicRelatedEventsRes()
}

type ListPublicSalePhasesRes interface {
	listPublicSalePhasesRes()
}

type ListPublicTicketCategoriesRes interface {
	listPublicTicketCategoriesRes()
}

type ListPublicUpcomingEventsRes interface {
	listPublicUpcomingEventsRes()
}

type PostponeOrgOccurrenceRes interface {
	postponeOrgOccurrenceRes()
}

type PublishOrgEventRes interface {
	publishOrgEventRes()
}

type RejectAdminOrganizerApplicationRes interface {
	rejectAdminOrganizerApplicationRes()
}

type RemoveOrgMemberRes interface {
	removeOrgMemberRes()
}

type RequestChangesAdminOrganizerApplicationRes interface {
	requestChangesAdminOrganizerApplicationRes()
}

type RescheduleOrgOccurrenceRes interface {
	rescheduleOrgOccurrenceRes()
}

type ResubmitMyOrganizerApplicationRes interface {
	resubmitMyOrganizerApplicationRes()
}

type StartOrgSalePhaseRes interface {
	startOrgSalePhaseRes()
}

type SuspendAdminOrganizerRes interface {
	suspendAdminOrganizerRes()
}

type SuspendOrgSalePhaseRes interface {
	suspendOrgSalePhaseRes()
}

type UpdateAdminCategoryRes interface {
	updateAdminCategoryRes()
}

type UpdateAdminCityRes interface {
	updateAdminCityRes()
}

type UpdateMyOrganizerApplicationRes interface {
	updateMyOrganizerApplicationRes()
}

type UpdateOrgEventRes interface {
	updateOrgEventRes()
}

type UpdateOrgMemberRes interface {
	updateOrgMemberRes()
}

type UpdateOrgOccurrenceRes interface {
	updateOrgOccurrenceRes()
}

type UpdateOrgSalePhaseRes interface {
	updateOrgSalePhaseRes()
}

type UpdateOrgTicketCategoryRes interface {
	updateOrgTicketCategoryRes()
}
