// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	CategoriesHandler
	CitiesHandler
	EventsHandler
	MembersHandler
	OccurrencesHandler
	OrdersHandler
	OrganizerApplicationsHandler
	OrganizersHandler
	ProfileHandler
	SalePhasesHandler
	StaffHandler
	TicketCategoriesHandler
	TicketsHandler
	// NewError creates *DefaultStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultStatusCode
}

// CategoriesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Categories
type CategoriesHandler interface {
	// ActivateAdminCategory implements activateAdminCategory operation.
	//
	// Activate a category.
	//
	// POST /admin/categories/{categoryId}/activate
	ActivateAdminCategory(ctx context.Context, params ActivateAdminCategoryParams) (ActivateAdminCategoryRes, error)
	// CreateAdminCategory implements createAdminCategory operation.
	//
	// Create a category.
	//
	// POST /admin/categories
	CreateAdminCategory(ctx context.Context, req *CreateCategoryRequest) (CreateAdminCategoryRes, error)
	// DeactivateAdminCategory implements deactivateAdminCategory operation.
	//
	// Deactivate a category.
	//
	// POST /admin/categories/{categoryId}/deactivate
	DeactivateAdminCategory(ctx context.Context, params DeactivateAdminCategoryParams) (DeactivateAdminCategoryRes, error)
	// GetAdminCategory implements getAdminCategory operation.
	//
	// Get a category.
	//
	// GET /admin/categories/{categoryId}
	GetAdminCategory(ctx context.Context, params GetAdminCategoryParams) (GetAdminCategoryRes, error)
	// ListAdminCategories implements listAdminCategories operation.
	//
	// List categories.
	//
	// GET /admin/categories
	ListAdminCategories(ctx context.Context) (ListAdminCategoriesRes, error)
	// ListPublicCategories implements listPublicCategories operation.
	//
	// List categories.
	//
	// GET /public/categories
	ListPublicCategories(ctx context.Context) (ListPublicCategoriesRes, error)
	// UpdateAdminCategory implements updateAdminCategory operation.
	//
	// Replace a category.
	//
	// PUT /admin/categories/{categoryId}
	UpdateAdminCategory(ctx context.Context, req *UpdateCategoryRequest, params UpdateAdminCategoryParams) (UpdateAdminCategoryRes, error)
}

// CitiesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Cities
type CitiesHandler interface {
	// ActivateAdminCity implements activateAdminCity operation.
	//
	// Activate a city.
	//
	// POST /admin/cities/{cityCode}/activate
	ActivateAdminCity(ctx context.Context, params ActivateAdminCityParams) (ActivateAdminCityRes, error)
	// CreateAdminCity implements createAdminCity operation.
	//
	// Create a city.
	//
	// POST /admin/cities
	CreateAdminCity(ctx context.Context) (CreateAdminCityRes, error)
	// DeactivateAdminCity implements deactivateAdminCity operation.
	//
	// Deactivate a city.
	//
	// POST /admin/cities/{cityCode}/deactivate
	DeactivateAdminCity(ctx context.Context, params DeactivateAdminCityParams) (DeactivateAdminCityRes, error)
	// GetAdminCity implements getAdminCity operation.
	//
	// Get a city.
	//
	// GET /admin/cities/{cityCode}
	GetAdminCity(ctx context.Context, params GetAdminCityParams) (GetAdminCityRes, error)
	// ListAdminCities implements listAdminCities operation.
	//
	// List cities.
	//
	// GET /admin/cities
	ListAdminCities(ctx context.Context) (ListAdminCitiesRes, error)
	// ListPublicCities implements listPublicCities operation.
	//
	// List cities.
	//
	// GET /public/cities
	ListPublicCities(ctx context.Context) (ListPublicCitiesRes, error)
	// UpdateAdminCity implements updateAdminCity operation.
	//
	// Update a city.
	//
	// PATCH /admin/cities/{cityCode}
	UpdateAdminCity(ctx context.Context, params UpdateAdminCityParams) (UpdateAdminCityRes, error)
}

// EventsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Events
type EventsHandler interface {
	// CloseOrgEvent implements closeOrgEvent operation.
	//
	// Close an event.
	//
	// POST /org/events/{eventId}/close
	CloseOrgEvent(ctx context.Context, params CloseOrgEventParams) (CloseOrgEventRes, error)
	// CreateOrgEvent implements createOrgEvent operation.
	//
	// Create an event.
	//
	// POST /org/organizers/{organizerId}/events
	CreateOrgEvent(ctx context.Context, params CreateOrgEventParams) (CreateOrgEventRes, error)
	// GetOrgEvent implements getOrgEvent operation.
	//
	// Get an event.
	//
	// GET /org/events/{eventId}
	GetOrgEvent(ctx context.Context, params GetOrgEventParams) (GetOrgEventRes, error)
	// GetPublicEvent implements getPublicEvent operation.
	//
	// Get an event.
	//
	// GET /public/events/{eventSlug}
	GetPublicEvent(ctx context.Context, params GetPublicEventParams) (GetPublicEventRes, error)
	// ListOrgEvents implements listOrgEvents operation.
	//
	// List events.
	//
	// GET /org/organizers/{organizerId}/events
	ListOrgEvents(ctx context.Context, params ListOrgEventsParams) (ListOrgEventsRes, error)
	// ListPublicEvents implements listPublicEvents operation.
	//
	// List events.
	//
	// GET /public/events
	ListPublicEvents(ctx context.Context, params ListPublicEventsParams) (ListPublicEventsRes, error)
	// ListPublicFeaturedEvents implements listPublicFeaturedEvents operation.
	//
	// List featured events.
	//
	// GET /public/events/featured
	ListPublicFeaturedEvents(ctx context.Context, params ListPublicFeaturedEventsParams) (ListPublicFeaturedEventsRes, error)
	// ListPublicRelatedEvents implements listPublicRelatedEvents operation.
	//
	// List related events.
	//
	// GET /public/events/{eventSlug}/related
	ListPublicRelatedEvents(ctx context.Context, params ListPublicRelatedEventsParams) (ListPublicRelatedEventsRes, error)
	// ListPublicUpcomingEvents implements listPublicUpcomingEvents operation.
	//
	// List upcoming events.
	//
	// GET /public/events/upcoming
	ListPublicUpcomingEvents(ctx context.Context, params ListPublicUpcomingEventsParams) (ListPublicUpcomingEventsRes, error)
	// PublishOrgEvent implements publishOrgEvent operation.
	//
	// Publish an event.
	//
	// POST /org/events/{eventId}/publish
	PublishOrgEvent(ctx context.Context, params PublishOrgEventParams) (PublishOrgEventRes, error)
	// UpdateOrgEvent implements updateOrgEvent operation.
	//
	// Update an event.
	//
	// PATCH /org/events/{eventId}
	UpdateOrgEvent(ctx context.Context, params UpdateOrgEventParams) (UpdateOrgEventRes, error)
}

// MembersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Members
type MembersHandler interface {
	// AddOrgMember implements addOrgMember operation.
	//
	// Adds an existing gotick account to the organizer, found by the email it registered with. Only owners
	// may change the member list.
	//
	// POST /org/organizers/{organizerId}/members
	AddOrgMember(ctx context.Context, req *AddOrganizerMemberRequest, params AddOrgMemberParams) (AddOrgMemberRes, error)
	// ListOrgMembers implements listOrgMembers operation.
	//
	// List members.
	//
	// GET /org/organizers/{organizerId}/members
	ListOrgMembers(ctx context.Context, params ListOrgMembersParams) (ListOrgMembersRes, error)
	// RemoveOrgMember implements removeOrgMember operation.
	//
	// Removing the last owner is refused: an organizer without an owner has nobody who can manage it.
	//
	// DELETE /org/organizers/{organizerId}/members/{accountId}
	RemoveOrgMember(ctx context.Context, params RemoveOrgMemberParams) (RemoveOrgMemberRes, error)
	// UpdateOrgMember implements updateOrgMember operation.
	//
	// Change a member's role.
	//
	// PATCH /org/organizers/{organizerId}/members/{accountId}
	UpdateOrgMember(ctx context.Context, req *UpdateOrganizerMemberRequest, params UpdateOrgMemberParams) (UpdateOrgMemberRes, error)
}

// OccurrencesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Occurrences
type OccurrencesHandler interface {
	// CancelOrgOccurrence implements cancelOrgOccurrence operation.
	//
	// Cancel an occurrence.
	//
	// POST /org/occurrences/{occurrenceId}/cancel
	CancelOrgOccurrence(ctx context.Context, params CancelOrgOccurrenceParams) (CancelOrgOccurrenceRes, error)
	// CreateOrgOccurrence implements createOrgOccurrence operation.
	//
	// Create an occurrence.
	//
	// POST /org/events/{eventId}/occurrences
	CreateOrgOccurrence(ctx context.Context, params CreateOrgOccurrenceParams) (CreateOrgOccurrenceRes, error)
	// GetOrgOccurrence implements getOrgOccurrence operation.
	//
	// Get an occurrence.
	//
	// GET /org/occurrences/{occurrenceId}
	GetOrgOccurrence(ctx context.Context, params GetOrgOccurrenceParams) (GetOrgOccurrenceRes, error)
	// ListOrgOccurrences implements listOrgOccurrences operation.
	//
	// List occurrences.
	//
	// GET /org/events/{eventId}/occurrences
	ListOrgOccurrences(ctx context.Context, params ListOrgOccurrencesParams) (ListOrgOccurrencesRes, error)
	// ListPublicEventOccurrences implements listPublicEventOccurrences operation.
	//
	// List event occurrences.
	//
	// GET /public/events/{eventSlug}/occurrences
	ListPublicEventOccurrences(ctx context.Context, params ListPublicEventOccurrencesParams) (ListPublicEventOccurrencesRes, error)
	// PostponeOrgOccurrence implements postponeOrgOccurrence operation.
	//
	// Postpone an occurrence.
	//
	// POST /org/occurrences/{occurrenceId}/postpone
	PostponeOrgOccurrence(ctx context.Context, params PostponeOrgOccurrenceParams) (PostponeOrgOccurrenceRes, error)
	// RescheduleOrgOccurrence implements rescheduleOrgOccurrence operation.
	//
	// Reschedule an occurrence.
	//
	// POST /org/occurrences/{occurrenceId}/reschedule
	RescheduleOrgOccurrence(ctx context.Context, params RescheduleOrgOccurrenceParams) (RescheduleOrgOccurrenceRes, error)
	// UpdateOrgOccurrence implements updateOrgOccurrence operation.
	//
	// Update an occurrence.
	//
	// PATCH /org/occurrences/{occurrenceId}
	UpdateOrgOccurrence(ctx context.Context, params UpdateOrgOccurrenceParams) (UpdateOrgOccurrenceRes, error)
}

// OrdersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Orders
type OrdersHandler interface {
	// CreateMyOrder implements createMyOrder operation.
	//
	// Create an order.
	//
	// POST /me/orders
	CreateMyOrder(ctx context.Context) (CreateMyOrderRes, error)
	// GetMyOrder implements getMyOrder operation.
	//
	// Get my order.
	//
	// GET /me/orders/{orderId}
	GetMyOrder(ctx context.Context, params GetMyOrderParams) (GetMyOrderRes, error)
	// ListMyOrders implements listMyOrders operation.
	//
	// List my orders.
	//
	// GET /me/orders
	ListMyOrders(ctx context.Context, params ListMyOrdersParams) (ListMyOrdersRes, error)
}

// OrganizerApplicationsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: OrganizerApplications
type OrganizerApplicationsHandler interface {
	// ApproveAdminOrganizerApplication implements approveAdminOrganizerApplication operation.
	//
	// Approve an organizer application.
	//
	// POST /admin/organizer-applications/{organizerApplicationId}/approve
	ApproveAdminOrganizerApplication(ctx context.Context, params ApproveAdminOrganizerApplicationParams) (ApproveAdminOrganizerApplicationRes, error)
	// CreateMyOrganizerApplication implements createMyOrganizerApplication operation.
	//
	// Submit an organizer application.
	//
	// POST /me/organizer-applications
	CreateMyOrganizerApplication(ctx context.Context) (CreateMyOrganizerApplicationRes, error)
	// GetMyOrganizerApplication implements getMyOrganizerApplication operation.
	//
	// Get my organizer application.
	//
	// GET /me/organizer-applications/{organizerApplicationId}
	GetMyOrganizerApplication(ctx context.Context, params GetMyOrganizerApplicationParams) (GetMyOrganizerApplicationRes, error)
	// ListAdminOrganizerApplications implements listAdminOrganizerApplications operation.
	//
	// List organizer applications.
	//
	// GET /admin/organizer-applications
	ListAdminOrganizerApplications(ctx context.Context, params ListAdminOrganizerApplicationsParams) (ListAdminOrganizerApplicationsRes, error)
	// ListMyOrganizerApplications implements listMyOrganizerApplications operation.
	//
	// List my organizer applications.
	//
	// GET /me/organizer-applications
	ListMyOrganizerApplications(ctx context.Context, params ListMyOrganizerApplicationsParams) (ListMyOrganizerApplicationsRes, error)
	// RejectAdminOrganizerApplication implements rejectAdminOrganizerApplication operation.
	//
	// Reject an organizer application.
	//
	// POST /admin/organizer-applications/{organizerApplicationId}/reject
	RejectAdminOrganizerApplication(ctx context.Context, params RejectAdminOrganizerApplicationParams) (RejectAdminOrganizerApplicationRes, error)
	// RequestChangesAdminOrganizerApplication implements requestChangesAdminOrganizerApplication operation.
	//
	// Request changes on an organizer application.
	//
	// POST /admin/organizer-applications/{organizerApplicationId}/request-changes
	RequestChangesAdminOrganizerApplication(ctx context.Context, params RequestChangesAdminOrganizerApplicationParams) (RequestChangesAdminOrganizerApplicationRes, error)
	// ResubmitMyOrganizerApplication implements resubmitMyOrganizerApplication operation.
	//
	// Resubmit my organizer application.
	//
	// POST /me/organizer-applications/{organizerApplicationId}/resubmit
	ResubmitMyOrganizerApplication(ctx context.Context, params ResubmitMyOrganizerApplicationParams) (ResubmitMyOrganizerApplicationRes, error)
	// UpdateMyOrganizerApplication implements updateMyOrganizerApplication operation.
	//
	// Update my organizer application.
	//
	// PATCH /me/organizer-applications/{organizerApplicationId}
	UpdateMyOrganizerApplication(ctx context.Context, params UpdateMyOrganizerApplicationParams) (UpdateMyOrganizerApplicationRes, error)
}

// OrganizersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Organizers
type OrganizersHandler interface {
	// ActivateAdminOrganizer implements activateAdminOrganizer operation.
	//
	// Activate an organizer.
	//
	// POST /admin/organizers/{organizerId}/activate
	ActivateAdminOrganizer(ctx context.Context, params ActivateAdminOrganizerParams) (ActivateAdminOrganizerRes, error)
	// GetPublicOrganizer implements getPublicOrganizer operation.
	//
	// Get an organizer.
	//
	// GET /public/organizers/{organizerSlug}
	GetPublicOrganizer(ctx context.Context, params GetPublicOrganizerParams) (GetPublicOrganizerRes, error)
	// ListAdminOrganizers implements listAdminOrganizers operation.
	//
	// List organizers.
	//
	// GET /admin/organizers
	ListAdminOrganizers(ctx context.Context, params ListAdminOrganizersParams) (ListAdminOrganizersRes, error)
	// ListPublicOrganizers implements listPublicOrganizers operation.
	//
	// List organizers.
	//
	// GET /public/organizers
	ListPublicOrganizers(ctx context.Context, params ListPublicOrganizersParams) (ListPublicOrganizersRes, error)
	// SuspendAdminOrganizer implements suspendAdminOrganizer operation.
	//
	// Suspend an organizer.
	//
	// POST /admin/organizers/{organizerId}/suspend
	SuspendAdminOrganizer(ctx context.Context, params SuspendAdminOrganizerParams) (SuspendAdminOrganizerRes, error)
}

// ProfileHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Profile
type ProfileHandler interface {
	// CreateMyProfile implements createMyProfile operation.
	//
	// Completes account setup for the signed-in identity. Email and phone number are taken from the
	// verified token, never from the body. Calling it again for an identity that already has a profile
	// returns the existing one.
	//
	// POST /me/profile
	CreateMyProfile(ctx context.Context, req *CreateMyProfileRequest) (CreateMyProfileRes, error)
	// GetMyProfile implements getMyProfile operation.
	//
	// Get my profile.
	//
	// GET /me/profile
	GetMyProfile(ctx context.Context) (GetMyProfileRes, error)
}

// SalePhasesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: SalePhases
type SalePhasesHandler interface {
	// CancelOrgSalePhase implements cancelOrgSalePhase operation.
	//
	// Cancel a sale phase.
	//
	// POST /org/sale-phases/{salePhaseId}/cancel
	CancelOrgSalePhase(ctx context.Context, params CancelOrgSalePhaseParams) (CancelOrgSalePhaseRes, error)
	// CreateOrgSalePhase implements createOrgSalePhase operation.
	//
	// Create a sale phase.
	//
	// POST /org/occurrences/{occurrenceId}/sale-phases
	CreateOrgSalePhase(ctx context.Context, params CreateOrgSalePhaseParams) (CreateOrgSalePhaseRes, error)
	// EndOrgSalePhase implements endOrgSalePhase operation.
	//
	// End a sale phase.
	//
	// POST /org/sale-phases/{salePhaseId}/end
	EndOrgSalePhase(ctx context.Context, params EndOrgSalePhaseParams) (EndOrgSalePhaseRes, error)
	// GetOrgSalePhase implements getOrgSalePhase operation.
	//
	// Get a sale phase.
	//
	// GET /org/sale-phases/{salePhaseId}
	GetOrgSalePhase(ctx context.Context, params GetOrgSalePhaseParams) (GetOrgSalePhaseRes, error)
	// ListOrgSalePhases implements listOrgSalePhases operation.
	//
	// List sale phases.
	//
	// GET /org/occurrences/{occurrenceId}/sale-phases
	ListOrgSalePhases(ctx context.Context, params ListOrgSalePhasesParams) (ListOrgSalePhasesRes, error)
	// ListPublicSalePhases implements listPublicSalePhases operation.
	//
	// List sale phases.
	//
	// GET /public/occurrences/{occurrenceId}/sale-phases
	ListPublicSalePhases(ctx context.Context, params ListPublicSalePhasesParams) (ListPublicSalePhasesRes, error)
	// StartOrgSalePhase implements startOrgSalePhase operation.
	//
	// Start a sale phase.
	//
	// POST /org/sale-phases/{salePhaseId}/start
	StartOrgSalePhase(ctx context.Context, params StartOrgSalePhaseParams) (StartOrgSalePhaseRes, error)
	// SuspendOrgSalePhase implements suspendOrgSalePhase operation.
	//
	// Suspend a sale phase.
	//
	// POST /org/sale-phases/{salePhaseId}/suspend
	SuspendOrgSalePhase(ctx context.Context, params SuspendOrgSalePhaseParams) (SuspendOrgSalePhaseRes, error)
	// UpdateOrgSalePhase implements updateOrgSalePhase operation.
	//
	// Update a sale phase.
	//
	// PATCH /org/sale-phases/{salePhaseId}
	UpdateOrgSalePhase(ctx context.Context, params UpdateOrgSalePhaseParams) (UpdateOrgSalePhaseRes, error)
}

// StaffHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Staff
type StaffHandler interface {
	// ListAdminStaff implements listAdminStaff operation.
	//
	// List platform staff.
	//
	// GET /admin/staff
	ListAdminStaff(ctx context.Context) (ListAdminStaffRes, error)
}

// TicketCategoriesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: TicketCategories
type TicketCategoriesHandler interface {
	// CreateOrgTicketCategory implements createOrgTicketCategory operation.
	//
	// Create a ticket category.
	//
	// POST /org/occurrences/{occurrenceId}/ticket-categories
	CreateOrgTicketCategory(ctx context.Context, params CreateOrgTicketCategoryParams) (CreateOrgTicketCategoryRes, error)
	// GetOrgTicketCategory implements getOrgTicketCategory operation.
	//
	// Get a ticket category.
	//
	// GET /org/ticket-categories/{ticketCategoryId}
	GetOrgTicketCategory(ctx context.Context, params GetOrgTicketCategoryParams) (GetOrgTicketCategoryRes, error)
	// ListOrgTicketCategories implements listOrgTicketCategories operation.
	//
	// List ticket categories.
	//
	// GET /org/occurrences/{occurrenceId}/ticket-categories
	ListOrgTicketCategories(ctx context.Context, params ListOrgTicketCategoriesParams) (ListOrgTicketCategoriesRes, error)
	// ListPublicTicketCategories implements listPublicTicketCategories operation.
	//
	// List ticket categories.
	//
	// GET /public/occurrences/{occurrenceId}/ticket-categories
	ListPublicTicketCategories(ctx context.Context, params ListPublicTicketCategoriesParams) (ListPublicTicketCategoriesRes, error)
	// UpdateOrgTicketCategory implements updateOrgTicketCategory operation.
	//
	// Update a ticket category.
	//
	// PATCH /org/ticket-categories/{ticketCategoryId}
	UpdateOrgTicketCategory(ctx context.Context, params UpdateOrgTicketCategoryParams) (UpdateOrgTicketCategoryRes, error)
}

// TicketsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Tickets
type TicketsHandler interface {
	// GetMyTicket implements getMyTicket operation.
	//
	// Get my ticket.
	//
	// GET /me/tickets/{ticketId}
	GetMyTicket(ctx context.Context, params GetMyTicketParams) (GetMyTicketRes, error)
	// ListMyTickets implements listMyTickets operation.
	//
	// List my tickets.
	//
	// GET /me/tickets
	ListMyTickets(ctx context.Context, params ListMyTicketsParams) (ListMyTicketsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
