// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivateAdminCategory implements activateAdminCategory operation.
//
// Activate a category.
//
// POST /admin/categories/{categoryId}/activate
func (UnimplementedHandler) ActivateAdminCategory(ctx context.Context, params ActivateAdminCategoryParams) (r ActivateAdminCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActivateAdminCity implements activateAdminCity operation.
//
// Activate a city.
//
// POST /admin/cities/{cityCode}/activate
func (UnimplementedHandler) ActivateAdminCity(ctx context.Context, params ActivateAdminCityParams) (r ActivateAdminCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActivateAdminOrganizer implements activateAdminOrganizer operation.
//
// Activate an organizer.
//
// POST /admin/organizers/{organizerId}/activate
func (UnimplementedHandler) ActivateAdminOrganizer(ctx context.Context, params ActivateAdminOrganizerParams) (r ActivateAdminOrganizerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddOrgMember implements addOrgMember operation.
//
// Adds an existing gotick account to the organizer, found by the email it registered with. Only owners
// may change the member list.
//
// POST /org/organizers/{organizerId}/members
func (UnimplementedHandler) AddOrgMember(ctx context.Context, req *AddOrganizerMemberRequest, params AddOrgMemberParams) (r AddOrgMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ApproveAdminOrganizerApplication implements approveAdminOrganizerApplication operation.
//
// Approve an organizer application.
//
// POST /admin/organizer-applications/{organizerApplicationId}/approve
func (UnimplementedHandler) ApproveAdminOrganizerApplication(ctx context.Context, params ApproveAdminOrganizerApplicationParams) (r ApproveAdminOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelOrgOccurrence implements cancelOrgOccurrence operation.
//
// Cancel an occurrence.
//
// POST /org/occurrences/{occurrenceId}/cancel
func (UnimplementedHandler) CancelOrgOccurrence(ctx context.Context, params CancelOrgOccurrenceParams) (r CancelOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelOrgSalePhase implements cancelOrgSalePhase operation.
//
// Cancel a sale phase.
//
// POST /org/sale-phases/{salePhaseId}/cancel
func (UnimplementedHandler) CancelOrgSalePhase(ctx context.Context, params CancelOrgSalePhaseParams) (r CancelOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CloseOrgEvent implements closeOrgEvent operation.
//
// Close an event.
//
// POST /org/events/{eventId}/close
func (UnimplementedHandler) CloseOrgEvent(ctx context.Context, params CloseOrgEventParams) (r CloseOrgEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminCategory implements createAdminCategory operation.
//
// Create a category.
//
// POST /admin/categories
func (UnimplementedHandler) CreateAdminCategory(ctx context.Context, req *CreateCategoryRequest) (r CreateAdminCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminCity implements createAdminCity operation.
//
// Create a city.
//
// POST /admin/cities
func (UnimplementedHandler) CreateAdminCity(ctx context.Context) (r CreateAdminCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMyOrder implements createMyOrder operation.
//
// Create an order.
//
// POST /me/orders
func (UnimplementedHandler) CreateMyOrder(ctx context.Context) (r CreateMyOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMyOrganizerApplication implements createMyOrganizerApplication operation.
//
// Submit an organizer application.
//
// POST /me/organizer-applications
func (UnimplementedHandler) CreateMyOrganizerApplication(ctx context.Context) (r CreateMyOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMyProfile implements createMyProfile operation.
//
// Completes account setup for the signed-in identity. Email and phone number are taken from the
// verified token, never from the body. Calling it again for an identity that already has a profile
// returns the existing one.
//
// POST /me/profile
func (UnimplementedHandler) CreateMyProfile(ctx context.Context, req *CreateMyProfileRequest) (r CreateMyProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrgEvent implements createOrgEvent operation.
//
// Create an event.
//
// POST /org/organizers/{organizerId}/events
func (UnimplementedHandler) CreateOrgEvent(ctx context.Context, params CreateOrgEventParams) (r CreateOrgEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrgOccurrence implements createOrgOccurrence operation.
//
// Create an occurrence.
//
// POST /org/events/{eventId}/occurrences
func (UnimplementedHandler) CreateOrgOccurrence(ctx context.Context, params CreateOrgOccurrenceParams) (r CreateOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrgSalePhase implements createOrgSalePhase operation.
//
// Create a sale phase.
//
// POST /org/occurrences/{occurrenceId}/sale-phases
func (UnimplementedHandler) CreateOrgSalePhase(ctx context.Context, params CreateOrgSalePhaseParams) (r CreateOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrgTicketCategory implements createOrgTicketCategory operation.
//
// Create a ticket category.
//
// POST /org/occurrences/{occurrenceId}/ticket-categories
func (UnimplementedHandler) CreateOrgTicketCategory(ctx context.Context, params CreateOrgTicketCategoryParams) (r CreateOrgTicketCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeactivateAdminCategory implements deactivateAdminCategory operation.
//
// Deactivate a category.
//
// POST /admin/categories/{categoryId}/deactivate
func (UnimplementedHandler) DeactivateAdminCategory(ctx context.Context, params DeactivateAdminCategoryParams) (r DeactivateAdminCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeactivateAdminCity implements deactivateAdminCity operation.
//
// Deactivate a city.
//
// POST /admin/cities/{cityCode}/deactivate
func (UnimplementedHandler) DeactivateAdminCity(ctx context.Context, params DeactivateAdminCityParams) (r DeactivateAdminCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EndOrgSalePhase implements endOrgSalePhase operation.
//
// End a sale phase.
//
// POST /org/sale-phases/{salePhaseId}/end
func (UnimplementedHandler) EndOrgSalePhase(ctx context.Context, params EndOrgSalePhaseParams) (r EndOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminCategory implements getAdminCategory operation.
//
// Get a category.
//
// GET /admin/categories/{categoryId}
func (UnimplementedHandler) GetAdminCategory(ctx context.Context, params GetAdminCategoryParams) (r GetAdminCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminCity implements getAdminCity operation.
//
// Get a city.
//
// GET /admin/cities/{cityCode}
func (UnimplementedHandler) GetAdminCity(ctx context.Context, params GetAdminCityParams) (r GetAdminCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyOrder implements getMyOrder operation.
//
// Get my order.
//
// GET /me/orders/{orderId}
func (UnimplementedHandler) GetMyOrder(ctx context.Context, params GetMyOrderParams) (r GetMyOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyOrganizerApplication implements getMyOrganizerApplication operation.
//
// Get my organizer application.
//
// GET /me/organizer-applications/{organizerApplicationId}
func (UnimplementedHandler) GetMyOrganizerApplication(ctx context.Context, params GetMyOrganizerApplicationParams) (r GetMyOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyProfile implements getMyProfile operation.
//
// Get my profile.
//
// GET /me/profile
func (UnimplementedHandler) GetMyProfile(ctx context.Context) (r GetMyProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyTicket implements getMyTicket operation.
//
// Get my ticket.
//
// GET /me/tickets/{ticketId}
func (UnimplementedHandler) GetMyTicket(ctx context.Context, params GetMyTicketParams) (r GetMyTicketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrgEvent implements getOrgEvent operation.
//
// Get an event.
//
// GET /org/events/{eventId}
func (UnimplementedHandler) GetOrgEvent(ctx context.Context, params GetOrgEventParams) (r GetOrgEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrgOccurrence implements getOrgOccurrence operation.
//
// Get an occurrence.
//
// GET /org/occurrences/{occurrenceId}
func (UnimplementedHandler) GetOrgOccurrence(ctx context.Context, params GetOrgOccurrenceParams) (r GetOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrgSalePhase implements getOrgSalePhase operation.
//
// Get a sale phase.
//
// GET /org/sale-phases/{salePhaseId}
func (UnimplementedHandler) GetOrgSalePhase(ctx context.Context, params GetOrgSalePhaseParams) (r GetOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrgTicketCategory implements getOrgTicketCategory operation.
//
// Get a ticket category.
//
// GET /org/ticket-categories/{ticketCategoryId}
func (UnimplementedHandler) GetOrgTicketCategory(ctx context.Context, params GetOrgTicketCategoryParams) (r GetOrgTicketCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPublicEvent implements getPublicEvent operation.
//
// Get an event.
//
// GET /public/events/{eventSlug}
func (UnimplementedHandler) GetPublicEvent(ctx context.Context, params GetPublicEventParams) (r GetPublicEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPublicOrganizer implements getPublicOrganizer operation.
//
// Get an organizer.
//
// GET /public/organizers/{organizerSlug}
func (UnimplementedHandler) GetPublicOrganizer(ctx context.Context, params GetPublicOrganizerParams) (r GetPublicOrganizerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminCategories implements listAdminCategories operation.
//
// List categories.
//
// GET /admin/categories
func (UnimplementedHandler) ListAdminCategories(ctx context.Context) (r ListAdminCategoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminCities implements listAdminCities operation.
//
// List cities.
//
// GET /admin/cities
func (UnimplementedHandler) ListAdminCities(ctx context.Context) (r ListAdminCitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminOrganizerApplications implements listAdminOrganizerApplications operation.
//
// List organizer applications.
//
// GET /admin/organizer-applications
func (UnimplementedHandler) ListAdminOrganizerApplications(ctx context.Context, params ListAdminOrganizerApplicationsParams) (r ListAdminOrganizerApplicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminOrganizers implements listAdminOrganizers operation.
//
// List organizers.
//
// GET /admin/organizers
func (UnimplementedHandler) ListAdminOrganizers(ctx context.Context, params ListAdminOrganizersParams) (r ListAdminOrganizersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminStaff implements listAdminStaff operation.
//
// List platform staff.
//
// GET /admin/staff
func (UnimplementedHandler) ListAdminStaff(ctx context.Context) (r ListAdminStaffRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyOrders implements listMyOrders operation.
//
// List my orders.
//
// GET /me/orders
func (UnimplementedHandler) ListMyOrders(ctx context.Context, params ListMyOrdersParams) (r ListMyOrdersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyOrganizerApplications implements listMyOrganizerApplications operation.
//
// List my organizer applications.
//
// GET /me/organizer-applications
func (UnimplementedHandler) ListMyOrganizerApplications(ctx context.Context, params ListMyOrganizerApplicationsParams) (r ListMyOrganizerApplicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyTickets implements listMyTickets operation.
//
// List my tickets.
//
// GET /me/tickets
func (UnimplementedHandler) ListMyTickets(ctx context.Context, params ListMyTicketsParams) (r ListMyTicketsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrgEvents implements listOrgEvents operation.
//
// List events.
//
// GET /org/organizers/{organizerId}/events
func (UnimplementedHandler) ListOrgEvents(ctx context.Context, params ListOrgEventsParams) (r ListOrgEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrgMembers implements listOrgMembers operation.
//
// List members.
//
// GET /org/organizers/{organizerId}/members
func (UnimplementedHandler) ListOrgMembers(ctx context.Context, params ListOrgMembersParams) (r ListOrgMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrgOccurrences implements listOrgOccurrences operation.
//
// List occurrences.
//
// GET /org/events/{eventId}/occurrences
func (UnimplementedHandler) ListOrgOccurrences(ctx context.Context, params ListOrgOccurrencesParams) (r ListOrgOccurrencesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrgSalePhases implements listOrgSalePhases operation.
//
// List sale phases.
//
// GET /org/occurrences/{occurrenceId}/sale-phases
func (UnimplementedHandler) ListOrgSalePhases(ctx context.Context, params ListOrgSalePhasesParams) (r ListOrgSalePhasesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrgTicketCategories implements listOrgTicketCategories operation.
//
// List ticket categories.
//
// GET /org/occurrences/{occurrenceId}/ticket-categories
func (UnimplementedHandler) ListOrgTicketCategories(ctx context.Context, params ListOrgTicketCategoriesParams) (r ListOrgTicketCategoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicCategories implements listPublicCategories operation.
//
// List categories.
//
// GET /public/categories
func (UnimplementedHandler) ListPublicCategories(ctx context.Context) (r ListPublicCategoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicCities implements listPublicCities operation.
//
// List cities.
//
// GET /public/cities
func (UnimplementedHandler) ListPublicCities(ctx context.Context) (r ListPublicCitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicEventOccurrences implements listPublicEventOccurrences operation.
//
// List event occurrences.
//
// GET /public/events/{eventSlug}/occurrences
func (UnimplementedHandler) ListPublicEventOccurrences(ctx context.Context, params ListPublicEventOccurrencesParams) (r ListPublicEventOccurrencesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicEvents implements listPublicEvents operation.
//
// List events.
//
// GET /public/events
func (UnimplementedHandler) ListPublicEvents(ctx context.Context, params ListPublicEventsParams) (r ListPublicEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicFeaturedEvents implements listPublicFeaturedEvents operation.
//
// List featured events.
//
// GET /public/events/featured
func (UnimplementedHandler) ListPublicFeaturedEvents(ctx context.Context, params ListPublicFeaturedEventsParams) (r ListPublicFeaturedEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicOrganizers implements listPublicOrganizers operation.
//
// List organizers.
//
// GET /public/organizers
func (UnimplementedHandler) ListPublicOrganizers(ctx context.Context, params ListPublicOrganizersParams) (r ListPublicOrganizersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicRelatedEvents implements listPublicRelatedEvents operation.
//
// List related events.
//
// GET /public/events/{eventSlug}/related
func (UnimplementedHandler) ListPublicRelatedEvents(ctx context.Context, params ListPublicRelatedEventsParams) (r ListPublicRelatedEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicSalePhases implements listPublicSalePhases operation.
//
// List sale phases.
//
// GET /public/occurrences/{occurrenceId}/sale-phases
func (UnimplementedHandler) ListPublicSalePhases(ctx context.Context, params ListPublicSalePhasesParams) (r ListPublicSalePhasesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicTicketCategories implements listPublicTicketCategories operation.
//
// List ticket categories.
//
// GET /public/occurrences/{occurrenceId}/ticket-categories
func (UnimplementedHandler) ListPublicTicketCategories(ctx context.Context, params ListPublicTicketCategoriesParams) (r ListPublicTicketCategoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicUpcomingEvents implements listPublicUpcomingEvents operation.
//
// List upcoming events.
//
// GET /public/events/upcoming
func (UnimplementedHandler) ListPublicUpcomingEvents(ctx context.Context, params ListPublicUpcomingEventsParams) (r ListPublicUpcomingEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostponeOrgOccurrence implements postponeOrgOccurrence operation.
//
// Postpone an occurrence.
//
// POST /org/occurrences/{occurrenceId}/postpone
func (UnimplementedHandler) PostponeOrgOccurrence(ctx context.Context, params PostponeOrgOccurrenceParams) (r PostponeOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PublishOrgEvent implements publishOrgEvent operation.
//
// Publish an event.
//
// POST /org/events/{eventId}/publish
func (UnimplementedHandler) PublishOrgEvent(ctx context.Context, params PublishOrgEventParams) (r PublishOrgEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RejectAdminOrganizerApplication implements rejectAdminOrganizerApplication operation.
//
// Reject an organizer application.
//
// POST /admin/organizer-applications/{organizerApplicationId}/reject
func (UnimplementedHandler) RejectAdminOrganizerApplication(ctx context.Context, params RejectAdminOrganizerApplicationParams) (r RejectAdminOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveOrgMember implements removeOrgMember operation.
//
// Removing the last owner is refused: an organizer without an owner has nobody who can manage it.
//
// DELETE /org/organizers/{organizerId}/members/{accountId}
func (UnimplementedHandler) RemoveOrgMember(ctx context.Context, params RemoveOrgMemberParams) (r RemoveOrgMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestChangesAdminOrganizerApplication implements requestChangesAdminOrganizerApplication operation.
//
// Request changes on an organizer application.
//
// POST /admin/organizer-applications/{organizerApplicationId}/request-changes
func (UnimplementedHandler) RequestChangesAdminOrganizerApplication(ctx context.Context, params RequestChangesAdminOrganizerApplicationParams) (r RequestChangesAdminOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RescheduleOrgOccurrence implements rescheduleOrgOccurrence operation.
//
// Reschedule an occurrence.
//
// POST /org/occurrences/{occurrenceId}/reschedule
func (UnimplementedHandler) RescheduleOrgOccurrence(ctx context.Context, params RescheduleOrgOccurrenceParams) (r RescheduleOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResubmitMyOrganizerApplication implements resubmitMyOrganizerApplication operation.
//
// Resubmit my organizer application.
//
// POST /me/organizer-applications/{organizerApplicationId}/resubmit
func (UnimplementedHandler) ResubmitMyOrganizerApplication(ctx context.Context, params ResubmitMyOrganizerApplicationParams) (r ResubmitMyOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartOrgSalePhase implements startOrgSalePhase operation.
//
// Start a sale phase.
//
// POST /org/sale-phases/{salePhaseId}/start
func (UnimplementedHandler) StartOrgSalePhase(ctx context.Context, params StartOrgSalePhaseParams) (r StartOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SuspendAdminOrganizer implements suspendAdminOrganizer operation.
//
// Suspend an organizer.
//
// POST /admin/organizers/{organizerId}/suspend
func (UnimplementedHandler) SuspendAdminOrganizer(ctx context.Context, params SuspendAdminOrganizerParams) (r SuspendAdminOrganizerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SuspendOrgSalePhase implements suspendOrgSalePhase operation.
//
// Suspend a sale phase.
//
// POST /org/sale-phases/{salePhaseId}/suspend
func (UnimplementedHandler) SuspendOrgSalePhase(ctx context.Context, params SuspendOrgSalePhaseParams) (r SuspendOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminCategory implements updateAdminCategory operation.
//
// Replace a category.
//
// PUT /admin/categories/{categoryId}
func (UnimplementedHandler) UpdateAdminCategory(ctx context.Context, req *UpdateCategoryRequest, params UpdateAdminCategoryParams) (r UpdateAdminCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminCity implements updateAdminCity operation.
//
// Update a city.
//
// PATCH /admin/cities/{cityCode}
func (UnimplementedHandler) UpdateAdminCity(ctx context.Context, params UpdateAdminCityParams) (r UpdateAdminCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMyOrganizerApplication implements updateMyOrganizerApplication operation.
//
// Update my organizer application.
//
// PATCH /me/organizer-applications/{organizerApplicationId}
func (UnimplementedHandler) UpdateMyOrganizerApplication(ctx context.Context, params UpdateMyOrganizerApplicationParams) (r UpdateMyOrganizerApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrgEvent implements updateOrgEvent operation.
//
// Update an event.
//
// PATCH /org/events/{eventId}
func (UnimplementedHandler) UpdateOrgEvent(ctx context.Context, params UpdateOrgEventParams) (r UpdateOrgEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrgMember implements updateOrgMember operation.
//
// Change a member's role.
//
// PATCH /org/organizers/{organizerId}/members/{accountId}
func (UnimplementedHandler) UpdateOrgMember(ctx context.Context, req *UpdateOrganizerMemberRequest, params UpdateOrgMemberParams) (r UpdateOrgMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrgOccurrence implements updateOrgOccurrence operation.
//
// Update an occurrence.
//
// PATCH /org/occurrences/{occurrenceId}
func (UnimplementedHandler) UpdateOrgOccurrence(ctx context.Context, params UpdateOrgOccurrenceParams) (r UpdateOrgOccurrenceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrgSalePhase implements updateOrgSalePhase operation.
//
// Update a sale phase.
//
// PATCH /org/sale-phases/{salePhaseId}
func (UnimplementedHandler) UpdateOrgSalePhase(ctx context.Context, params UpdateOrgSalePhaseParams) (r UpdateOrgSalePhaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrgTicketCategory implements updateOrgTicketCategory operation.
//
// Update a ticket category.
//
// PATCH /org/ticket-categories/{ticketCategoryId}
func (UnimplementedHandler) UpdateOrgTicketCategory(ctx context.Context, params UpdateOrgTicketCategoryParams) (r UpdateOrgTicketCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *DefaultStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *DefaultStatusCode) {
	r = new(DefaultStatusCode)
	return r
}
