// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *DefaultStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type ActivateAdminCategoryForbidden Error

func (*ActivateAdminCategoryForbidden) activateAdminCategoryRes() {}

type ActivateAdminCategoryNotFound Error

func (*ActivateAdminCategoryNotFound) activateAdminCategoryRes() {}

type ActivateAdminCategoryUnauthorized Error

func (*ActivateAdminCategoryUnauthorized) activateAdminCategoryRes() {}

type ActivateAdminCityForbidden Error

func (*ActivateAdminCityForbidden) activateAdminCityRes() {}

type ActivateAdminCityNotFound Error

func (*ActivateAdminCityNotFound) activateAdminCityRes() {}

type ActivateAdminCityUnauthorized Error

func (*ActivateAdminCityUnauthorized) activateAdminCityRes() {}

type ActivateAdminOrganizerForbidden Error

func (*ActivateAdminOrganizerForbidden) activateAdminOrganizerRes() {}

type ActivateAdminOrganizerNotFound Error

func (*ActivateAdminOrganizerNotFound) activateAdminOrganizerRes() {}

type ActivateAdminOrganizerUnauthorized Error

func (*ActivateAdminOrganizerUnauthorized) activateAdminOrganizerRes() {}

type ApproveAdminOrganizerApplicationForbidden Error

func (*ApproveAdminOrganizerApplicationForbidden) approveAdminOrganizerApplicationRes() {}

type ApproveAdminOrganizerApplicationNotFound Error

func (*ApproveAdminOrganizerApplicationNotFound) approveAdminOrganizerApplicationRes() {}

type ApproveAdminOrganizerApplicationUnauthorized Error

func (*ApproveAdminOrganizerApplicationUnauthorized) approveAdminOrganizerApplicationRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CancelOrgOccurrenceForbidden Error

func (*CancelOrgOccurrenceForbidden) cancelOrgOccurrenceRes() {}

type CancelOrgOccurrenceNotFound Error

func (*CancelOrgOccurrenceNotFound) cancelOrgOccurrenceRes() {}

type CancelOrgOccurrenceUnauthorized Error

func (*CancelOrgOccurrenceUnauthorized) cancelOrgOccurrenceRes() {}

type CancelOrgSalePhaseForbidden Error

func (*CancelOrgSalePhaseForbidden) cancelOrgSalePhaseRes() {}

type CancelOrgSalePhaseNotFound Error

func (*CancelOrgSalePhaseNotFound) cancelOrgSalePhaseRes() {}

type CancelOrgSalePhaseUnauthorized Error

func (*CancelOrgSalePhaseUnauthorized) cancelOrgSalePhaseRes() {}

// Ref: #/components/schemas/Category
type Category struct {
	ID           int            `json:"id"`
	Name         string         `json:"name"`
	Slug         Slug           `json:"slug"`
	Icon         OptString      `json:"icon"`
	DisplayOrder int            `json:"displayOrder"`
	Status       CategoryStatus `json:"status"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Category) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Category) GetName() string {
	return s.Name
}

// GetSlug returns the value of Slug.
func (s *Category) GetSlug() Slug {
	return s.Slug
}

// GetIcon returns the value of Icon.
func (s *Category) GetIcon() OptString {
	return s.Icon
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Category) GetDisplayOrder() int {
	return s.DisplayOrder
}

// GetStatus returns the value of Status.
func (s *Category) GetStatus() CategoryStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Category) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Category) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Category) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Category) SetName(val string) {
	s.Name = val
}

// SetSlug sets the value of Slug.
func (s *Category) SetSlug(val Slug) {
	s.Slug = val
}

// SetIcon sets the value of Icon.
func (s *Category) SetIcon(val OptString) {
	s.Icon = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Category) SetDisplayOrder(val int) {
	s.DisplayOrder = val
}

// SetStatus sets the value of Status.
func (s *Category) SetStatus(val CategoryStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Category) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Category) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Category) activateAdminCategoryRes()   {}
func (*Category) createAdminCategoryRes()     {}
func (*Category) deactivateAdminCategoryRes() {}
func (*Category) getAdminCategoryRes()        {}
func (*Category) updateAdminCategoryRes()     {}

type CategoryList []Category

func (*CategoryList) listAdminCategoriesRes() {}

// Ref: #/components/schemas/CategoryStatus
type CategoryStatus string

const (
	CategoryStatusActive   CategoryStatus = "active"
	CategoryStatusInactive CategoryStatus = "inactive"
)

// AllValues returns all CategoryStatus values.
func (CategoryStatus) AllValues() []CategoryStatus {
	return []CategoryStatus{
		CategoryStatusActive,
		CategoryStatusInactive,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CategoryStatus) MarshalText() ([]byte, error) {
	switch s {
	case CategoryStatusActive:
		return []byte(s), nil
	case CategoryStatusInactive:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CategoryStatus) UnmarshalText(data []byte) error {
	switch CategoryStatus(data) {
	case CategoryStatusActive:
		*s = CategoryStatusActive
		return nil
	case CategoryStatusInactive:
		*s = CategoryStatusInactive
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/City
type City struct {
	Code       string     `json:"code"`
	Name       string     `json:"name"`
	NameEn     OptString  `json:"nameEn"`
	FullName   string     `json:"fullName"`
	FullNameEn OptString  `json:"fullNameEn"`
	Status     CityStatus `json:"status"`
}

// GetCode returns the value of Code.
func (s *City) GetCode() string {
	return s.Code
}

// GetName returns the value of Name.
func (s *City) GetName() string {
	return s.Name
}

// GetNameEn returns the value of NameEn.
func (s *City) GetNameEn() OptString {
	return s.NameEn
}

// GetFullName returns the value of FullName.
func (s *City) GetFullName() string {
	return s.FullName
}

// GetFullNameEn returns the value of FullNameEn.
func (s *City) GetFullNameEn() OptString {
	return s.FullNameEn
}

// GetStatus returns the value of Status.
func (s *City) GetStatus() CityStatus {
	return s.Status
}

// SetCode sets the value of Code.
func (s *City) SetCode(val string) {
	s.Code = val
}

// SetName sets the value of Name.
func (s *City) SetName(val string) {
	s.Name = val
}

// SetNameEn sets the value of NameEn.
func (s *City) SetNameEn(val OptString) {
	s.NameEn = val
}

// SetFullName sets the value of FullName.
func (s *City) SetFullName(val string) {
	s.FullName = val
}

// SetFullNameEn sets the value of FullNameEn.
func (s *City) SetFullNameEn(val OptString) {
	s.FullNameEn = val
}

// SetStatus sets the value of Status.
func (s *City) SetStatus(val CityStatus) {
	s.Status = val
}

func (*City) activateAdminCityRes()   {}
func (*City) createAdminCityRes()     {}
func (*City) deactivateAdminCityRes() {}
func (*City) getAdminCityRes()        {}
func (*City) updateAdminCityRes()     {}

type CityList []City

func (*CityList) listAdminCitiesRes() {}

// Ref: #/components/schemas/CityStatus
type CityStatus string

const (
	CityStatusActive   CityStatus = "active"
	CityStatusInactive CityStatus = "inactive"
)

// AllValues returns all CityStatus values.
func (CityStatus) AllValues() []CityStatus {
	return []CityStatus{
		CityStatusActive,
		CityStatusInactive,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CityStatus) MarshalText() ([]byte, error) {
	switch s {
	case CityStatusActive:
		return []byte(s), nil
	case CityStatusInactive:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CityStatus) UnmarshalText(data []byte) error {
	switch CityStatus(data) {
	case CityStatusActive:
		*s = CityStatusActive
		return nil
	case CityStatusInactive:
		*s = CityStatusInactive
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CloseOrgEventForbidden Error

func (*CloseOrgEventForbidden) closeOrgEventRes() {}

type CloseOrgEventNotFound Error

func (*CloseOrgEventNotFound) closeOrgEventRes() {}

type CloseOrgEventUnauthorized Error

func (*CloseOrgEventUnauthorized) closeOrgEventRes() {}

type CreateAdminCategoryBadRequest Error

func (*CreateAdminCategoryBadRequest) createAdminCategoryRes() {}

type CreateAdminCategoryForbidden Error

func (*CreateAdminCategoryForbidden) createAdminCategoryRes() {}

type CreateAdminCategoryUnauthorized Error

func (*CreateAdminCategoryUnauthorized) createAdminCategoryRes() {}

type CreateAdminCityBadRequest Error

func (*CreateAdminCityBadRequest) createAdminCityRes() {}

type CreateAdminCityForbidden Error

func (*CreateAdminCityForbidden) createAdminCityRes() {}

type CreateAdminCityUnauthorized Error

func (*CreateAdminCityUnauthorized) createAdminCityRes() {}

type CreateMyOrderBadRequest Error

func (*CreateMyOrderBadRequest) createMyOrderRes() {}

type CreateMyOrderUnauthorized Error

func (*CreateMyOrderUnauthorized) createMyOrderRes() {}

type CreateMyOrganizerApplicationBadRequest Error

func (*CreateMyOrganizerApplicationBadRequest) createMyOrganizerApplicationRes() {}

type CreateMyOrganizerApplicationUnauthorized Error

func (*CreateMyOrganizerApplicationUnauthorized) createMyOrganizerApplicationRes() {}

type CreateOrgEventBadRequest Error

func (*CreateOrgEventBadRequest) createOrgEventRes() {}

type CreateOrgEventForbidden Error

func (*CreateOrgEventForbidden) createOrgEventRes() {}

type CreateOrgEventUnauthorized Error

func (*CreateOrgEventUnauthorized) createOrgEventRes() {}

type CreateOrgOccurrenceBadRequest Error

func (*CreateOrgOccurrenceBadRequest) createOrgOccurrenceRes() {}

type CreateOrgOccurrenceForbidden Error

func (*CreateOrgOccurrenceForbidden) createOrgOccurrenceRes() {}

type CreateOrgOccurrenceNotFound Error

func (*CreateOrgOccurrenceNotFound) createOrgOccurrenceRes() {}

type CreateOrgOccurrenceUnauthorized Error

func (*CreateOrgOccurrenceUnauthorized) createOrgOccurrenceRes() {}

type CreateOrgSalePhaseBadRequest Error

func (*CreateOrgSalePhaseBadRequest) createOrgSalePhaseRes() {}

type CreateOrgSalePhaseForbidden Error

func (*CreateOrgSalePhaseForbidden) createOrgSalePhaseRes() {}

type CreateOrgSalePhaseNotFound Error

func (*CreateOrgSalePhaseNotFound) createOrgSalePhaseRes() {}

type CreateOrgSalePhaseUnauthorized Error

func (*CreateOrgSalePhaseUnauthorized) createOrgSalePhaseRes() {}

type CreateOrgTicketCategoryBadRequest Error

func (*CreateOrgTicketCategoryBadRequest) createOrgTicketCategoryRes() {}

type CreateOrgTicketCategoryForbidden Error

func (*CreateOrgTicketCategoryForbidden) createOrgTicketCategoryRes() {}

type CreateOrgTicketCategoryNotFound Error

func (*CreateOrgTicketCategoryNotFound) createOrgTicketCategoryRes() {}

type CreateOrgTicketCategoryUnauthorized Error

func (*CreateOrgTicketCategoryUnauthorized) createOrgTicketCategoryRes() {}

type DeactivateAdminCategoryForbidden Error

func (*DeactivateAdminCategoryForbidden) deactivateAdminCategoryRes() {}

type DeactivateAdminCategoryNotFound Error

func (*DeactivateAdminCategoryNotFound) deactivateAdminCategoryRes() {}

type DeactivateAdminCategoryUnauthorized Error

func (*DeactivateAdminCategoryUnauthorized) deactivateAdminCategoryRes() {}

type DeactivateAdminCityForbidden Error

func (*DeactivateAdminCityForbidden) deactivateAdminCityRes() {}

type DeactivateAdminCityNotFound Error

func (*DeactivateAdminCityNotFound) deactivateAdminCityRes() {}

type DeactivateAdminCityUnauthorized Error

func (*DeactivateAdminCityUnauthorized) deactivateAdminCityRes() {}

// DefaultStatusCode wraps Error with StatusCode.
type DefaultStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *DefaultStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *DefaultStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DefaultStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *DefaultStatusCode) SetResponse(val Error) {
	s.Response = val
}

type EndOrgSalePhaseForbidden Error

func (*EndOrgSalePhaseForbidden) endOrgSalePhaseRes() {}

type EndOrgSalePhaseNotFound Error

func (*EndOrgSalePhaseNotFound) endOrgSalePhaseRes() {}

type EndOrgSalePhaseUnauthorized Error

func (*EndOrgSalePhaseUnauthorized) endOrgSalePhaseRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getMyProfileRes()             {}
func (*Error) getPublicEventRes()           {}
func (*Error) getPublicOrganizerRes()       {}
func (*Error) listPublicCategoriesRes()     {}
func (*Error) listPublicCitiesRes()         {}
func (*Error) listPublicEventsRes()         {}
func (*Error) listPublicFeaturedEventsRes() {}
func (*Error) listPublicOrganizersRes()     {}
func (*Error) listPublicUpcomingEventsRes() {}

// Ref: #/components/schemas/Event
type Event struct {
	ID          UUID        `json:"id"`
	Name        string      `json:"name"`
	Slug        Slug        `json:"slug"`
	Description string      `json:"description"`
	Image       string      `json:"image"`
	Status      EventStatus `json:"status"`
	IsListed    bool        `json:"isListed"`
	IsFeatured  bool        `json:"isFeatured"`
	PublishedAt OptDateTime `json:"publishedAt"`
	ClosedAt    OptDateTime `json:"closedAt"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Event) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Event) GetName() string {
	return s.Name
}

// GetSlug returns the value of Slug.
func (s *Event) GetSlug() Slug {
	return s.Slug
}

// GetDescription returns the value of Description.
func (s *Event) GetDescription() string {
	return s.Description
}

// GetImage returns the value of Image.
func (s *Event) GetImage() string {
	return s.Image
}

// GetStatus returns the value of Status.
func (s *Event) GetStatus() EventStatus {
	return s.Status
}

// GetIsListed returns the value of IsListed.
func (s *Event) GetIsListed() bool {
	return s.IsListed
}

// GetIsFeatured returns the value of IsFeatured.
func (s *Event) GetIsFeatured() bool {
	return s.IsFeatured
}

// GetPublishedAt returns the value of PublishedAt.
func (s *Event) GetPublishedAt() OptDateTime {
	return s.PublishedAt
}

// GetClosedAt returns the value of ClosedAt.
func (s *Event) GetClosedAt() OptDateTime {
	return s.ClosedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Event) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Event) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Event) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Event) SetName(val string) {
	s.Name = val
}

// SetSlug sets the value of Slug.
func (s *Event) SetSlug(val Slug) {
	s.Slug = val
}

// SetDescription sets the value of Description.
func (s *Event) SetDescription(val string) {
	s.Description = val
}

// SetImage sets the value of Image.
func (s *Event) SetImage(val string) {
	s.Image = val
}

// SetStatus sets the value of Status.
func (s *Event) SetStatus(val EventStatus) {
	s.Status = val
}

// SetIsListed sets the value of IsListed.
func (s *Event) SetIsListed(val bool) {
	s.IsListed = val
}

// SetIsFeatured sets the value of IsFeatured.
func (s *Event) SetIsFeatured(val bool) {
	s.IsFeatured = val
}

// SetPublishedAt sets the value of PublishedAt.
func (s *Event) SetPublishedAt(val OptDateTime) {
	s.PublishedAt = val
}

// SetClosedAt sets the value of ClosedAt.
func (s *Event) SetClosedAt(val OptDateTime) {
	s.ClosedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Event) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Event) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Event) closeOrgEventRes()   {}
func (*Event) createOrgEventRes()  {}
func (*Event) getOrgEventRes()     {}
func (*Event) publishOrgEventRes() {}
func (*Event) updateOrgEventRes()  {}

type EventList []Event

func (*EventList) listOrgEventsRes() {}

// Ref: #/components/schemas/EventStatus
type EventStatus string

const (
	EventStatusDraft     EventStatus = "draft"
	EventStatusPublished EventStatus = "published"
	EventStatusClosed    EventStatus = "closed"
)

// AllValues returns all EventStatus values.
func (EventStatus) AllValues() []EventStatus {
	return []EventStatus{
		EventStatusDraft,
		EventStatusPublished,
		EventStatusClosed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EventStatus) MarshalText() ([]byte, error) {
	switch s {
	case EventStatusDraft:
		return []byte(s), nil
	case EventStatusPublished:
		return []byte(s), nil
	case EventStatusClosed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EventStatus) UnmarshalText(data []byte) error {
	switch EventStatus(data) {
	case EventStatusDraft:
		*s = EventStatusDraft
		return nil
	case EventStatusPublished:
		*s = EventStatusPublished
		return nil
	case EventStatusClosed:
		*s = EventStatusClosed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetAdminCategoryForbidden Error

func (*GetAdminCategoryForbidden) getAdminCategoryRes() {}

type GetAdminCategoryNotFound Error

func (*GetAdminCategoryNotFound) getAdminCategoryRes() {}

type GetAdminCategoryUnauthorized Error

func (*GetAdminCategoryUnauthorized) getAdminCategoryRes() {}

type GetAdminCityForbidden Error

func (*GetAdminCityForbidden) getAdminCityRes() {}

type GetAdminCityNotFound Error

func (*GetAdminCityNotFound) getAdminCityRes() {}

type GetAdminCityUnauthorized Error

func (*GetAdminCityUnauthorized) getAdminCityRes() {}

type GetMyOrderNotFound Error

func (*GetMyOrderNotFound) getMyOrderRes() {}

type GetMyOrderUnauthorized Error

func (*GetMyOrderUnauthorized) getMyOrderRes() {}

type GetMyOrganizerApplicationNotFound Error

func (*GetMyOrganizerApplicationNotFound) getMyOrganizerApplicationRes() {}

type GetMyOrganizerApplicationUnauthorized Error

func (*GetMyOrganizerApplicationUnauthorized) getMyOrganizerApplicationRes() {}

type GetMyTicketNotFound Error

func (*GetMyTicketNotFound) getMyTicketRes() {}

type GetMyTicketUnauthorized Error

func (*GetMyTicketUnauthorized) getMyTicketRes() {}

type GetOrgEventForbidden Error

func (*GetOrgEventForbidden) getOrgEventRes() {}

type GetOrgEventNotFound Error

func (*GetOrgEventNotFound) getOrgEventRes() {}

type GetOrgEventUnauthorized Error

func (*GetOrgEventUnauthorized) getOrgEventRes() {}

type GetOrgOccurrenceForbidden Error

func (*GetOrgOccurrenceForbidden) getOrgOccurrenceRes() {}

type GetOrgOccurrenceNotFound Error

func (*GetOrgOccurrenceNotFound) getOrgOccurrenceRes() {}

type GetOrgOccurrenceUnauthorized Error

func (*GetOrgOccurrenceUnauthorized) getOrgOccurrenceRes() {}

type GetOrgSalePhaseForbidden Error

func (*GetOrgSalePhaseForbidden) getOrgSalePhaseRes() {}

type GetOrgSalePhaseNotFound Error

func (*GetOrgSalePhaseNotFound) getOrgSalePhaseRes() {}

type GetOrgSalePhaseUnauthorized Error

func (*GetOrgSalePhaseUnauthorized) getOrgSalePhaseRes() {}

type GetOrgTicketCategoryForbidden Error

func (*GetOrgTicketCategoryForbidden) getOrgTicketCategoryRes() {}

type GetOrgTicketCategoryNotFound Error

func (*GetOrgTicketCategoryNotFound) getOrgTicketCategoryRes() {}

type GetOrgTicketCategoryUnauthorized Error

func (*GetOrgTicketCategoryUnauthorized) getOrgTicketCategoryRes() {}

type ListAdminCategoriesForbidden Error

func (*ListAdminCategoriesForbidden) listAdminCategoriesRes() {}

type ListAdminCategoriesUnauthorized Error

func (*ListAdminCategoriesUnauthorized) listAdminCategoriesRes() {}

type ListAdminCitiesForbidden Error

func (*ListAdminCitiesForbidden) listAdminCitiesRes() {}

type ListAdminCitiesUnauthorized Error

func (*ListAdminCitiesUnauthorized) listAdminCitiesRes() {}

type ListAdminOrganizerApplicationsBadRequest Error

func (*ListAdminOrganizerApplicationsBadRequest) listAdminOrganizerApplicationsRes() {}

type ListAdminOrganizerApplicationsForbidden Error

func (*ListAdminOrganizerApplicationsForbidden) listAdminOrganizerApplicationsRes() {}

type ListAdminOrganizerApplicationsUnauthorized Error

func (*ListAdminOrganizerApplicationsUnauthorized) listAdminOrganizerApplicationsRes() {}

type ListAdminOrganizersBadRequest Error

func (*ListAdminOrganizersBadRequest) listAdminOrganizersRes() {}

type ListAdminOrganizersForbidden Error

func (*ListAdminOrganizersForbidden) listAdminOrganizersRes() {}

type ListAdminOrganizersUnauthorized Error

func (*ListAdminOrganizersUnauthorized) listAdminOrganizersRes() {}

type ListMyOrdersBadRequest Error

func (*ListMyOrdersBadRequest) listMyOrdersRes() {}

type ListMyOrdersUnauthorized Error

func (*ListMyOrdersUnauthorized) listMyOrdersRes() {}

type ListMyOrganizerApplicationsBadRequest Error

func (*ListMyOrganizerApplicationsBadRequest) listMyOrganizerApplicationsRes() {}

type ListMyOrganizerApplicationsUnauthorized Error

func (*ListMyOrganizerApplicationsUnauthorized) listMyOrganizerApplicationsRes() {}

type ListMyTicketsBadRequest Error

func (*ListMyTicketsBadRequest) listMyTicketsRes() {}

type ListMyTicketsUnauthorized Error

func (*ListMyTicketsUnauthorized) listMyTicketsRes() {}

type ListOrgEventsBadRequest Error

func (*ListOrgEventsBadRequest) listOrgEventsRes() {}

type ListOrgEventsForbidden Error

func (*ListOrgEventsForbidden) listOrgEventsRes() {}

type ListOrgEventsUnauthorized Error

func (*ListOrgEventsUnauthorized) listOrgEventsRes() {}

type ListOrgOccurrencesBadRequest Error

func (*ListOrgOccurrencesBadRequest) listOrgOccurrencesRes() {}

type ListOrgOccurrencesForbidden Error

func (*ListOrgOccurrencesForbidden) listOrgOccurrencesRes() {}

type ListOrgOccurrencesNotFound Error

func (*ListOrgOccurrencesNotFound) listOrgOccurrencesRes() {}

type ListOrgOccurrencesUnauthorized Error

func (*ListOrgOccurrencesUnauthorized) listOrgOccurrencesRes() {}

type ListOrgSalePhasesBadRequest Error

func (*ListOrgSalePhasesBadRequest) listOrgSalePhasesRes() {}

type ListOrgSalePhasesForbidden Error

func (*ListOrgSalePhasesForbidden) listOrgSalePhasesRes() {}

type ListOrgSalePhasesNotFound Error

func (*ListOrgSalePhasesNotFound) listOrgSalePhasesRes() {}

type ListOrgSalePhasesUnauthorized Error

func (*ListOrgSalePhasesUnauthorized) listOrgSalePhasesRes() {}

type ListOrgTicketCategoriesBadRequest Error

func (*ListOrgTicketCategoriesBadRequest) listOrgTicketCategoriesRes() {}

type ListOrgTicketCategoriesForbidden Error

func (*ListOrgTicketCategoriesForbidden) listOrgTicketCategoriesRes() {}

type ListOrgTicketCategoriesNotFound Error

func (*ListOrgTicketCategoriesNotFound) listOrgTicketCategoriesRes() {}

type ListOrgTicketCategoriesUnauthorized Error

func (*ListOrgTicketCategoriesUnauthorized) listOrgTicketCategoriesRes() {}

type ListPublicEventOccurrencesBadRequest Error

func (*ListPublicEventOccurrencesBadRequest) listPublicEventOccurrencesRes() {}

type ListPublicEventOccurrencesNotFound Error

func (*ListPublicEventOccurrencesNotFound) listPublicEventOccurrencesRes() {}

type ListPublicRelatedEventsBadRequest Error

func (*ListPublicRelatedEventsBadRequest) listPublicRelatedEventsRes() {}

type ListPublicRelatedEventsNotFound Error

func (*ListPublicRelatedEventsNotFound) listPublicRelatedEventsRes() {}

type ListPublicSalePhasesBadRequest Error

func (*ListPublicSalePhasesBadRequest) listPublicSalePhasesRes() {}

type ListPublicSalePhasesNotFound Error

func (*ListPublicSalePhasesNotFound) listPublicSalePhasesRes() {}

type ListPublicTicketCategoriesBadRequest Error

func (*ListPublicTicketCategoriesBadRequest) listPublicTicketCategoriesRes() {}

type ListPublicTicketCategoriesNotFound Error

func (*ListPublicTicketCategoriesNotFound) listPublicTicketCategoriesRes() {}

// Ref: #/components/schemas/MyOrder
type MyOrder struct {
	ID            UUID          `json:"id"`
	TotalAmount   int64         `json:"totalAmount"`
	Status        OrderStatus   `json:"status"`
	HoldExpiresAt OptDateTime   `json:"holdExpiresAt"`
	Items         []MyOrderItem `json:"items"`
	CreatedAt     time.Time     `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *MyOrder) GetID() UUID {
	return s.ID
}

// GetTotalAmount returns the value of TotalAmount.
func (s *MyOrder) GetTotalAmount() int64 {
	return s.TotalAmount
}

// GetStatus returns the value of Status.
func (s *MyOrder) GetStatus() OrderStatus {
	return s.Status
}

// GetHoldExpiresAt returns the value of HoldExpiresAt.
func (s *MyOrder) GetHoldExpiresAt() OptDateTime {
	return s.HoldExpiresAt
}

// GetItems returns the value of Items.
func (s *MyOrder) GetItems() []MyOrderItem {
	return s.Items
}

// GetCreatedAt returns the value of CreatedAt.
func (s *MyOrder) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *MyOrder) SetID(val UUID) {
	s.ID = val
}

// SetTotalAmount sets the value of TotalAmount.
func (s *MyOrder) SetTotalAmount(val int64) {
	s.TotalAmount = val
}

// SetStatus sets the value of Status.
func (s *MyOrder) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetHoldExpiresAt sets the value of HoldExpiresAt.
func (s *MyOrder) SetHoldExpiresAt(val OptDateTime) {
	s.HoldExpiresAt = val
}

// SetItems sets the value of Items.
func (s *MyOrder) SetItems(val []MyOrderItem) {
	s.Items = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *MyOrder) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*MyOrder) createMyOrderRes() {}
func (*MyOrder) getMyOrderRes()    {}

// Ref: #/components/schemas/MyOrderItem
type MyOrderItem struct {
	ID        UUID  `json:"id"`
	Quantity  int   `json:"quantity"`
	UnitPrice int64 `json:"unitPrice"`
}

// GetID returns the value of ID.
func (s *MyOrderItem) GetID() UUID {
	return s.ID
}

// GetQuantity returns the value of Quantity.
func (s *MyOrderItem) GetQuantity() int {
	return s.Quantity
}

// GetUnitPrice returns the value of UnitPrice.
func (s *MyOrderItem) GetUnitPrice() int64 {
	return s.UnitPrice
}

// SetID sets the value of ID.
func (s *MyOrderItem) SetID(val UUID) {
	s.ID = val
}

// SetQuantity sets the value of Quantity.
func (s *MyOrderItem) SetQuantity(val int) {
	s.Quantity = val
}

// SetUnitPrice sets the value of UnitPrice.
func (s *MyOrderItem) SetUnitPrice(val int64) {
	s.UnitPrice = val
}

type MyOrderList []MyOrder

func (*MyOrderList) listMyOrdersRes() {}

// Ref: #/components/schemas/MyOrganizerApplication
type MyOrganizerApplication struct {
	ID         UUID                       `json:"id"`
	Status     OrganizerApplicationStatus `json:"status"`
	ReviewNote string                     `json:"reviewNote"`
	ReviewedAt OptDateTime                `json:"reviewedAt"`
	Organizer  Organizer                  `json:"organizer"`
	CreatedAt  time.Time                  `json:"createdAt"`
	UpdatedAt  time.Time                  `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *MyOrganizerApplication) GetID() UUID {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *MyOrganizerApplication) GetStatus() OrganizerApplicationStatus {
	return s.Status
}

// GetReviewNote returns the value of ReviewNote.
func (s *MyOrganizerApplication) GetReviewNote() string {
	return s.ReviewNote
}

// GetReviewedAt returns the value of ReviewedAt.
func (s *MyOrganizerApplication) GetReviewedAt() OptDateTime {
	return s.ReviewedAt
}

// GetOrganizer returns the value of Organizer.
func (s *MyOrganizerApplication) GetOrganizer() Organizer {
	return s.Organizer
}

// GetCreatedAt returns the value of CreatedAt.
func (s *MyOrganizerApplication) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *MyOrganizerApplication) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *MyOrganizerApplication) SetID(val UUID) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *MyOrganizerApplication) SetStatus(val OrganizerApplicationStatus) {
	s.Status = val
}

// SetReviewNote sets the value of ReviewNote.
func (s *MyOrganizerApplication) SetReviewNote(val string) {
	s.ReviewNote = val
}

// SetReviewedAt sets the value of ReviewedAt.
func (s *MyOrganizerApplication) SetReviewedAt(val OptDateTime) {
	s.ReviewedAt = val
}

// SetOrganizer sets the value of Organizer.
func (s *MyOrganizerApplication) SetOrganizer(val Organizer) {
	s.Organizer = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *MyOrganizerApplication) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *MyOrganizerApplication) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*MyOrganizerApplication) createMyOrganizerApplicationRes()   {}
func (*MyOrganizerApplication) getMyOrganizerApplicationRes()      {}
func (*MyOrganizerApplication) resubmitMyOrganizerApplicationRes() {}
func (*MyOrganizerApplication) updateMyOrganizerApplicationRes()   {}

type MyOrganizerApplicationList []MyOrganizerApplication

func (*MyOrganizerApplicationList) listMyOrganizerApplicationsRes() {}

// Ref: #/components/schemas/MyProfile
type MyProfile struct {
	ID       UUID   `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

// GetID returns the value of ID.
func (s *MyProfile) GetID() UUID {
	return s.ID
}

// GetFullName returns the value of FullName.
func (s *MyProfile) GetFullName() string {
	return s.FullName
}

// GetEmail returns the value of Email.
func (s *MyProfile) GetEmail() string {
	return s.Email
}

// GetAvatar returns the value of Avatar.
func (s *MyProfile) GetAvatar() string {
	return s.Avatar
}

// SetID sets the value of ID.
func (s *MyProfile) SetID(val UUID) {
	s.ID = val
}

// SetFullName sets the value of FullName.
func (s *MyProfile) SetFullName(val string) {
	s.FullName = val
}

// SetEmail sets the value of Email.
func (s *MyProfile) SetEmail(val string) {
	s.Email = val
}

// SetAvatar sets the value of Avatar.
func (s *MyProfile) SetAvatar(val string) {
	s.Avatar = val
}

func (*MyProfile) getMyProfileRes() {}

// Ref: #/components/schemas/MyTicket
type MyTicket struct {
	ID       UUID         `json:"id"`
	QrCode   string       `json:"qrCode"`
	Status   TicketStatus `json:"status"`
	IssuedAt time.Time    `json:"issuedAt"`
	UsedAt   OptDateTime  `json:"usedAt"`
}

// GetID returns the value of ID.
func (s *MyTicket) GetID() UUID {
	return s.ID
}

// GetQrCode returns the value of QrCode.
func (s *MyTicket) GetQrCode() string {
	return s.QrCode
}

// GetStatus returns the value of Status.
func (s *MyTicket) GetStatus() TicketStatus {
	return s.Status
}

// GetIssuedAt returns the value of IssuedAt.
func (s *MyTicket) GetIssuedAt() time.Time {
	return s.IssuedAt
}

// GetUsedAt returns the value of UsedAt.
func (s *MyTicket) GetUsedAt() OptDateTime {
	return s.UsedAt
}

// SetID sets the value of ID.
func (s *MyTicket) SetID(val UUID) {
	s.ID = val
}

// SetQrCode sets the value of QrCode.
func (s *MyTicket) SetQrCode(val string) {
	s.QrCode = val
}

// SetStatus sets the value of Status.
func (s *MyTicket) SetStatus(val TicketStatus) {
	s.Status = val
}

// SetIssuedAt sets the value of IssuedAt.
func (s *MyTicket) SetIssuedAt(val time.Time) {
	s.IssuedAt = val
}

// SetUsedAt sets the value of UsedAt.
func (s *MyTicket) SetUsedAt(val OptDateTime) {
	s.UsedAt = val
}

func (*MyTicket) getMyTicketRes() {}

type MyTicketList []MyTicket

func (*MyTicketList) listMyTicketsRes() {}

// Ref: #/components/schemas/Occurrence
type Occurrence struct {
	ID                 UUID             `json:"id"`
	Name               string           `json:"name"`
	StartTime          time.Time        `json:"startTime"`
	EndTime            time.Time        `json:"endTime"`
	VenueName          string           `json:"venueName"`
	VenueAddress       string           `json:"venueAddress"`
	Status             OccurrenceStatus `json:"status"`
	WaitingRoomEnabled bool             `json:"waitingRoomEnabled"`
	CanceledAt         OptDateTime      `json:"canceledAt"`
	CreatedAt          time.Time        `json:"createdAt"`
	UpdatedAt          time.Time        `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Occurrence) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Occurrence) GetName() string {
	return s.Name
}

// GetStartTime returns the value of StartTime.
func (s *Occurrence) GetStartTime() time.Time {
	return s.StartTime
}

// GetEndTime returns the value of EndTime.
func (s *Occurrence) GetEndTime() time.Time {
	return s.EndTime
}

// GetVenueName returns the value of VenueName.
func (s *Occurrence) GetVenueName() string {
	return s.VenueName
}

// GetVenueAddress returns the value of VenueAddress.
func (s *Occurrence) GetVenueAddress() string {
	return s.VenueAddress
}

// GetStatus returns the value of Status.
func (s *Occurrence) GetStatus() OccurrenceStatus {
	return s.Status
}

// GetWaitingRoomEnabled returns the value of WaitingRoomEnabled.
func (s *Occurrence) GetWaitingRoomEnabled() bool {
	return s.WaitingRoomEnabled
}

// GetCanceledAt returns the value of CanceledAt.
func (s *Occurrence) GetCanceledAt() OptDateTime {
	return s.CanceledAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Occurrence) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Occurrence) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Occurrence) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Occurrence) SetName(val string) {
	s.Name = val
}

// SetStartTime sets the value of StartTime.
func (s *Occurrence) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetEndTime sets the value of EndTime.
func (s *Occurrence) SetEndTime(val time.Time) {
	s.EndTime = val
}

// SetVenueName sets the value of VenueName.
func (s *Occurrence) SetVenueName(val string) {
	s.VenueName = val
}

// SetVenueAddress sets the value of VenueAddress.
func (s *Occurrence) SetVenueAddress(val string) {
	s.VenueAddress = val
}

// SetStatus sets the value of Status.
func (s *Occurrence) SetStatus(val OccurrenceStatus) {
	s.Status = val
}

// SetWaitingRoomEnabled sets the value of WaitingRoomEnabled.
func (s *Occurrence) SetWaitingRoomEnabled(val bool) {
	s.WaitingRoomEnabled = val
}

// SetCanceledAt sets the value of CanceledAt.
func (s *Occurrence) SetCanceledAt(val OptDateTime) {
	s.CanceledAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Occurrence) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Occurrence) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Occurrence) cancelOrgOccurrenceRes()     {}
func (*Occurrence) createOrgOccurrenceRes()     {}
func (*Occurrence) getOrgOccurrenceRes()        {}
func (*Occurrence) postponeOrgOccurrenceRes()   {}
func (*Occurrence) rescheduleOrgOccurrenceRes() {}
func (*Occurrence) updateOrgOccurrenceRes()     {}

type OccurrenceList []Occurrence

func (*OccurrenceList) listOrgOccurrencesRes() {}

// Ref: #/components/schemas/OccurrenceStatus
type OccurrenceStatus string

const (
	OccurrenceStatusScheduled OccurrenceStatus = "scheduled"
	OccurrenceStatusOnGoing   OccurrenceStatus = "on_going"
	OccurrenceStatusEnded     OccurrenceStatus = "ended"
	OccurrenceStatusCanceled  OccurrenceStatus = "canceled"
	OccurrenceStatusPostponed OccurrenceStatus = "postponed"
)

// AllValues returns all OccurrenceStatus values.
func (OccurrenceStatus) AllValues() []OccurrenceStatus {
	return []OccurrenceStatus{
		OccurrenceStatusScheduled,
		OccurrenceStatusOnGoing,
		OccurrenceStatusEnded,
		OccurrenceStatusCanceled,
		OccurrenceStatusPostponed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OccurrenceStatus) MarshalText() ([]byte, error) {
	switch s {
	case OccurrenceStatusScheduled:
		return []byte(s), nil
	case OccurrenceStatusOnGoing:
		return []byte(s), nil
	case OccurrenceStatusEnded:
		return []byte(s), nil
	case OccurrenceStatusCanceled:
		return []byte(s), nil
	case OccurrenceStatusPostponed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OccurrenceStatus) UnmarshalText(data []byte) error {
	switch OccurrenceStatus(data) {
	case OccurrenceStatusScheduled:
		*s = OccurrenceStatusScheduled
		return nil
	case OccurrenceStatusOnGoing:
		*s = OccurrenceStatusOnGoing
		return nil
	case OccurrenceStatusEnded:
		*s = OccurrenceStatusEnded
		return nil
	case OccurrenceStatusCanceled:
		*s = OccurrenceStatusCanceled
		return nil
	case OccurrenceStatusPostponed:
		*s = OccurrenceStatusPostponed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OrderStatus
type OrderStatus string

const (
	OrderStatusPendingPayment OrderStatus = "pending_payment"
	OrderStatusPaid           OrderStatus = "paid"
	OrderStatusCanceled       OrderStatus = "canceled"
	OrderStatusExpired        OrderStatus = "expired"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPendingPayment,
		OrderStatusPaid,
		OrderStatusCanceled,
		OrderStatusExpired,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPendingPayment:
		return []byte(s), nil
	case OrderStatusPaid:
		return []byte(s), nil
	case OrderStatusCanceled:
		return []byte(s), nil
	case OrderStatusExpired:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPendingPayment:
		*s = OrderStatusPendingPayment
		return nil
	case OrderStatusPaid:
		*s = OrderStatusPaid
		return nil
	case OrderStatusCanceled:
		*s = OrderStatusCanceled
		return nil
	case OrderStatusExpired:
		*s = OrderStatusExpired
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Organizer
type Organizer struct {
	ID            UUID                   `json:"id"`
	Name          string                 `json:"name"`
	Description   string                 `json:"description"`
	OrganizerType OrganizerType          `json:"organizerType"`
	Logo          string                 `json:"logo"`
	Email         string                 `json:"email"`
	Phone         string                 `json:"phone"`
	PublicContact OrganizerPublicContact `json:"publicContact"`
	Status        OrganizerStatus        `json:"status"`
	ActivatedAt   OptDateTime            `json:"activatedAt"`
	SuspendedAt   OptDateTime            `json:"suspendedAt"`
	CreatedAt     time.Time              `json:"createdAt"`
	UpdatedAt     time.Time              `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Organizer) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Organizer) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Organizer) GetDescription() string {
	return s.Description
}

// GetOrganizerType returns the value of OrganizerType.
func (s *Organizer) GetOrganizerType() OrganizerType {
	return s.OrganizerType
}

// GetLogo returns the value of Logo.
func (s *Organizer) GetLogo() string {
	return s.Logo
}

// GetEmail returns the value of Email.
func (s *Organizer) GetEmail() string {
	return s.Email
}

// GetPhone returns the value of Phone.
func (s *Organizer) GetPhone() string {
	return s.Phone
}

// GetPublicContact returns the value of PublicContact.
func (s *Organizer) GetPublicContact() OrganizerPublicContact {
	return s.PublicContact
}

// GetStatus returns the value of Status.
func (s *Organizer) GetStatus() OrganizerStatus {
	return s.Status
}

// GetActivatedAt returns the value of ActivatedAt.
func (s *Organizer) GetActivatedAt() OptDateTime {
	return s.ActivatedAt
}

// GetSuspendedAt returns the value of SuspendedAt.
func (s *Organizer) GetSuspendedAt() OptDateTime {
	return s.SuspendedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Organizer) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Organizer) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Organizer) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Organizer) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Organizer) SetDescription(val string) {
	s.Description = val
}

// SetOrganizerType sets the value of OrganizerType.
func (s *Organizer) SetOrganizerType(val OrganizerType) {
	s.OrganizerType = val
}

// SetLogo sets the value of Logo.
func (s *Organizer) SetLogo(val string) {
	s.Logo = val
}

// SetEmail sets the value of Email.
func (s *Organizer) SetEmail(val string) {
	s.Email = val
}

// SetPhone sets the value of Phone.
func (s *Organizer) SetPhone(val string) {
	s.Phone = val
}

// SetPublicContact sets the value of PublicContact.
func (s *Organizer) SetPublicContact(val OrganizerPublicContact) {
	s.PublicContact = val
}

// SetStatus sets the value of Status.
func (s *Organizer) SetStatus(val OrganizerStatus) {
	s.Status = val
}

// SetActivatedAt sets the value of ActivatedAt.
func (s *Organizer) SetActivatedAt(val OptDateTime) {
	s.ActivatedAt = val
}

// SetSuspendedAt sets the value of SuspendedAt.
func (s *Organizer) SetSuspendedAt(val OptDateTime) {
	s.SuspendedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Organizer) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Organizer) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Organizer) activateAdminOrganizerRes() {}
func (*Organizer) suspendAdminOrganizerRes()  {}

// Ref: #/components/schemas/OrganizerApplication
type OrganizerApplication struct {
	ID         UUID                       `json:"id"`
	Status     OrganizerApplicationStatus `json:"status"`
	ReviewNote string                     `json:"reviewNote"`
	ReviewedAt OptDateTime                `json:"reviewedAt"`
	CreatedAt  time.Time                  `json:"createdAt"`
	UpdatedAt  time.Time                  `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *OrganizerApplication) GetID() UUID {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *OrganizerApplication) GetStatus() OrganizerApplicationStatus {
	return s.Status
}

// GetReviewNote returns the value of ReviewNote.
func (s *OrganizerApplication) GetReviewNote() string {
	return s.ReviewNote
}

// GetReviewedAt returns the value of ReviewedAt.
func (s *OrganizerApplication) GetReviewedAt() OptDateTime {
	return s.ReviewedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrganizerApplication) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *OrganizerApplication) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *OrganizerApplication) SetID(val UUID) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *OrganizerApplication) SetStatus(val OrganizerApplicationStatus) {
	s.Status = val
}

// SetReviewNote sets the value of ReviewNote.
func (s *OrganizerApplication) SetReviewNote(val string) {
	s.ReviewNote = val
}

// SetReviewedAt sets the value of ReviewedAt.
func (s *OrganizerApplication) SetReviewedAt(val OptDateTime) {
	s.ReviewedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrganizerApplication) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *OrganizerApplication) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*OrganizerApplication) approveAdminOrganizerApplicationRes()        {}
func (*OrganizerApplication) rejectAdminOrganizerApplicationRes()         {}
func (*OrganizerApplication) requestChangesAdminOrganizerApplicationRes() {}

type OrganizerApplicationList []OrganizerApplication

func (*OrganizerApplicationList) listAdminOrganizerApplicationsRes() {}

// Ref: #/components/schemas/OrganizerApplicationStatus
type OrganizerApplicationStatus string

const (
	OrganizerApplicationStatusPending          OrganizerApplicationStatus = "pending"
	OrganizerApplicationStatusApproved         OrganizerApplicationStatus = "approved"
	OrganizerApplicationStatusChangesRequested OrganizerApplicationStatus = "changes_requested"
	OrganizerApplicationStatusRejected         OrganizerApplicationStatus = "rejected"
)

// AllValues returns all OrganizerApplicationStatus values.
func (OrganizerApplicationStatus) AllValues() []OrganizerApplicationStatus {
	return []OrganizerApplicationStatus{
		OrganizerApplicationStatusPending,
		OrganizerApplicationStatusApproved,
		OrganizerApplicationStatusChangesRequested,
		OrganizerApplicationStatusRejected,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrganizerApplicationStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrganizerApplicationStatusPending:
		return []byte(s), nil
	case OrganizerApplicationStatusApproved:
		return []byte(s), nil
	case OrganizerApplicationStatusChangesRequested:
		return []byte(s), nil
	case OrganizerApplicationStatusRejected:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrganizerApplicationStatus) UnmarshalText(data []byte) error {
	switch OrganizerApplicationStatus(data) {
	case OrganizerApplicationStatusPending:
		*s = OrganizerApplicationStatusPending
		return nil
	case OrganizerApplicationStatusApproved:
		*s = OrganizerApplicationStatusApproved
		return nil
	case OrganizerApplicationStatusChangesRequested:
		*s = OrganizerApplicationStatusChangesRequested
		return nil
	case OrganizerApplicationStatusRejected:
		*s = OrganizerApplicationStatusRejected
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type OrganizerList []Organizer

func (*OrganizerList) listAdminOrganizersRes() {}

type OrganizerPublicContact map[string]jx.Raw

func (s *OrganizerPublicContact) init() OrganizerPublicContact {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/OrganizerStatus
type OrganizerStatus string

const (
	OrganizerStatusPendingRegistration OrganizerStatus = "pending_registration"
	OrganizerStatusActive              OrganizerStatus = "active"
	OrganizerStatusSuspended           OrganizerStatus = "suspended"
)

// AllValues returns all OrganizerStatus values.
func (OrganizerStatus) AllValues() []OrganizerStatus {
	return []OrganizerStatus{
		OrganizerStatusPendingRegistration,
		OrganizerStatusActive,
		OrganizerStatusSuspended,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrganizerStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrganizerStatusPendingRegistration:
		return []byte(s), nil
	case OrganizerStatusActive:
		return []byte(s), nil
	case OrganizerStatusSuspended:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrganizerStatus) UnmarshalText(data []byte) error {
	switch OrganizerStatus(data) {
	case OrganizerStatusPendingRegistration:
		*s = OrganizerStatusPendingRegistration
		return nil
	case OrganizerStatusActive:
		*s = OrganizerStatusActive
		return nil
	case OrganizerStatusSuspended:
		*s = OrganizerStatusSuspended
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/OrganizerType
type OrganizerType string

const (
	OrganizerTypeIndividual   OrganizerType = "individual"
	OrganizerTypeOrganization OrganizerType = "organization"
)

// AllValues returns all OrganizerType values.
func (OrganizerType) AllValues() []OrganizerType {
	return []OrganizerType{
		OrganizerTypeIndividual,
		OrganizerTypeOrganization,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrganizerType) MarshalText() ([]byte, error) {
	switch s {
	case OrganizerTypeIndividual:
		return []byte(s), nil
	case OrganizerTypeOrganization:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrganizerType) UnmarshalText(data []byte) error {
	switch OrganizerType(data) {
	case OrganizerTypeIndividual:
		*s = OrganizerTypeIndividual
		return nil
	case OrganizerTypeOrganization:
		*s = OrganizerTypeOrganization
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PostponeOrgOccurrenceForbidden Error

func (*PostponeOrgOccurrenceForbidden) postponeOrgOccurrenceRes() {}

type PostponeOrgOccurrenceNotFound Error

func (*PostponeOrgOccurrenceNotFound) postponeOrgOccurrenceRes() {}

type PostponeOrgOccurrenceUnauthorized Error

func (*PostponeOrgOccurrenceUnauthorized) postponeOrgOccurrenceRes() {}

// Ref: #/components/schemas/PublicCategory
type PublicCategory struct {
	ID           int       `json:"id"`
	Name         string    `json:"name"`
	Slug         Slug      `json:"slug"`
	Icon         OptString `json:"icon"`
	DisplayOrder int       `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *PublicCategory) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *PublicCategory) GetName() string {
	return s.Name
}

// GetSlug returns the value of Slug.
func (s *PublicCategory) GetSlug() Slug {
	return s.Slug
}

// GetIcon returns the value of Icon.
func (s *PublicCategory) GetIcon() OptString {
	return s.Icon
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *PublicCategory) GetDisplayOrder() int {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *PublicCategory) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PublicCategory) SetName(val string) {
	s.Name = val
}

// SetSlug sets the value of Slug.
func (s *PublicCategory) SetSlug(val Slug) {
	s.Slug = val
}

// SetIcon sets the value of Icon.
func (s *PublicCategory) SetIcon(val OptString) {
	s.Icon = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *PublicCategory) SetDisplayOrder(val int) {
	s.DisplayOrder = val
}

type PublicCategoryList []PublicCategory

func (*PublicCategoryList) listPublicCategoriesRes() {}

// Ref: #/components/schemas/PublicCity
type PublicCity struct {
	Code       string    `json:"code"`
	Name       string    `json:"name"`
	NameEn     OptString `json:"nameEn"`
	FullName   string    `json:"fullName"`
	FullNameEn OptString `json:"fullNameEn"`
}

// GetCode returns the value of Code.
func (s *PublicCity) GetCode() string {
	return s.Code
}

// GetName returns the value of Name.
func (s *PublicCity) GetName() string {
	return s.Name
}

// GetNameEn returns the value of NameEn.
func (s *PublicCity) GetNameEn() OptString {
	return s.NameEn
}

// GetFullName returns the value of FullName.
func (s *PublicCity) GetFullName() string {
	return s.FullName
}

// GetFullNameEn returns the value of FullNameEn.
func (s *PublicCity) GetFullNameEn() OptString {
	return s.FullNameEn
}

// SetCode sets the value of Code.
func (s *PublicCity) SetCode(val string) {
	s.Code = val
}

// SetName sets the value of Name.
func (s *PublicCity) SetName(val string) {
	s.Name = val
}

// SetNameEn sets the value of NameEn.
func (s *PublicCity) SetNameEn(val OptString) {
	s.NameEn = val
}

// SetFullName sets the value of FullName.
func (s *PublicCity) SetFullName(val string) {
	s.FullName = val
}

// SetFullNameEn sets the value of FullNameEn.
func (s *PublicCity) SetFullNameEn(val OptString) {
	s.FullNameEn = val
}

type PublicCityList []PublicCity

func (*PublicCityList) listPublicCitiesRes() {}

// Ref: #/components/schemas/PublicEvent
type PublicEvent struct {
	ID               UUID           `json:"id"`
	Slug             Slug           `json:"slug"`
	Name             string         `json:"name"`
	Description      OptString      `json:"description"`
	Image            string         `json:"image"`
	Status           EventStatus    `json:"status"`
	IsFeatured       bool           `json:"isFeatured"`
	Category         PublicCategory `json:"category"`
	Cities           []PublicCity   `json:"cities"`
	EarlierStartTime OptDateTime    `json:"earlierStartTime"`
	LatestEndTime    OptDateTime    `json:"latestEndTime"`
}

// GetID returns the value of ID.
func (s *PublicEvent) GetID() UUID {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s *PublicEvent) GetSlug() Slug {
	return s.Slug
}

// GetName returns the value of Name.
func (s *PublicEvent) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *PublicEvent) GetDescription() OptString {
	return s.Description
}

// GetImage returns the value of Image.
func (s *PublicEvent) GetImage() string {
	return s.Image
}

// GetStatus returns the value of Status.
func (s *PublicEvent) GetStatus() EventStatus {
	return s.Status
}

// GetIsFeatured returns the value of IsFeatured.
func (s *PublicEvent) GetIsFeatured() bool {
	return s.IsFeatured
}

// GetCategory returns the value of Category.
func (s *PublicEvent) GetCategory() PublicCategory {
	return s.Category
}

// GetCities returns the value of Cities.
func (s *PublicEvent) GetCities() []PublicCity {
	return s.Cities
}

// GetEarlierStartTime returns the value of EarlierStartTime.
func (s *PublicEvent) GetEarlierStartTime() OptDateTime {
	return s.EarlierStartTime
}

// GetLatestEndTime returns the value of LatestEndTime.
func (s *PublicEvent) GetLatestEndTime() OptDateTime {
	return s.LatestEndTime
}

// SetID sets the value of ID.
func (s *PublicEvent) SetID(val UUID) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *PublicEvent) SetSlug(val Slug) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *PublicEvent) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *PublicEvent) SetDescription(val OptString) {
	s.Description = val
}

// SetImage sets the value of Image.
func (s *PublicEvent) SetImage(val string) {
	s.Image = val
}

// SetStatus sets the value of Status.
func (s *PublicEvent) SetStatus(val EventStatus) {
	s.Status = val
}

// SetIsFeatured sets the value of IsFeatured.
func (s *PublicEvent) SetIsFeatured(val bool) {
	s.IsFeatured = val
}

// SetCategory sets the value of Category.
func (s *PublicEvent) SetCategory(val PublicCategory) {
	s.Category = val
}

// SetCities sets the value of Cities.
func (s *PublicEvent) SetCities(val []PublicCity) {
	s.Cities = val
}

// SetEarlierStartTime sets the value of EarlierStartTime.
func (s *PublicEvent) SetEarlierStartTime(val OptDateTime) {
	s.EarlierStartTime = val
}

// SetLatestEndTime sets the value of LatestEndTime.
func (s *PublicEvent) SetLatestEndTime(val OptDateTime) {
	s.LatestEndTime = val
}

// Merged schema.
// Ref: #/components/schemas/PublicEventDetail
type PublicEventDetail struct {
	ID               UUID               `json:"id"`
	Slug             Slug               `json:"slug"`
	Name             string             `json:"name"`
	Description      OptString          `json:"description"`
	Image            string             `json:"image"`
	Status           EventStatus        `json:"status"`
	IsFeatured       bool               `json:"isFeatured"`
	Category         PublicCategory     `json:"category"`
	Cities           []PublicCity       `json:"cities"`
	EarlierStartTime OptDateTime        `json:"earlierStartTime"`
	LatestEndTime    OptDateTime        `json:"latestEndTime"`
	Organizer        PublicOrganizer    `json:"organizer"`
	Occurrences      []PublicOccurrence `json:"occurrences"`
}

// GetID returns the value of ID.
func (s *PublicEventDetail) GetID() UUID {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s *PublicEventDetail) GetSlug() Slug {
	return s.Slug
}

// GetName returns the value of Name.
func (s *PublicEventDetail) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *PublicEventDetail) GetDescription() OptString {
	return s.Description
}

// GetImage returns the value of Image.
func (s *PublicEventDetail) GetImage() string {
	return s.Image
}

// GetStatus returns the value of Status.
func (s *PublicEventDetail) GetStatus() EventStatus {
	return s.Status
}

// GetIsFeatured returns the value of IsFeatured.
func (s *PublicEventDetail) GetIsFeatured() bool {
	return s.IsFeatured
}

// GetCategory returns the value of Category.
func (s *PublicEventDetail) GetCategory() PublicCategory {
	return s.Category
}

// GetCities returns the value of Cities.
func (s *PublicEventDetail) GetCities() []PublicCity {
	return s.Cities
}

// GetEarlierStartTime returns the value of EarlierStartTime.
func (s *PublicEventDetail) GetEarlierStartTime() OptDateTime {
	return s.EarlierStartTime
}

// GetLatestEndTime returns the value of LatestEndTime.
func (s *PublicEventDetail) GetLatestEndTime() OptDateTime {
	return s.LatestEndTime
}

// GetOrganizer returns the value of Organizer.
func (s *PublicEventDetail) GetOrganizer() PublicOrganizer {
	return s.Organizer
}

// GetOccurrences returns the value of Occurrences.
func (s *PublicEventDetail) GetOccurrences() []PublicOccurrence {
	return s.Occurrences
}

// SetID sets the value of ID.
func (s *PublicEventDetail) SetID(val UUID) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *PublicEventDetail) SetSlug(val Slug) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *PublicEventDetail) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *PublicEventDetail) SetDescription(val OptString) {
	s.Description = val
}

// SetImage sets the value of Image.
func (s *PublicEventDetail) SetImage(val string) {
	s.Image = val
}

// SetStatus sets the value of Status.
func (s *PublicEventDetail) SetStatus(val EventStatus) {
	s.Status = val
}

// SetIsFeatured sets the value of IsFeatured.
func (s *PublicEventDetail) SetIsFeatured(val bool) {
	s.IsFeatured = val
}

// SetCategory sets the value of Category.
func (s *PublicEventDetail) SetCategory(val PublicCategory) {
	s.Category = val
}

// SetCities sets the value of Cities.
func (s *PublicEventDetail) SetCities(val []PublicCity) {
	s.Cities = val
}

// SetEarlierStartTime sets the value of EarlierStartTime.
func (s *PublicEventDetail) SetEarlierStartTime(val OptDateTime) {
	s.EarlierStartTime = val
}

// SetLatestEndTime sets the value of LatestEndTime.
func (s *PublicEventDetail) SetLatestEndTime(val OptDateTime) {
	s.LatestEndTime = val
}

// SetOrganizer sets the value of Organizer.
func (s *PublicEventDetail) SetOrganizer(val PublicOrganizer) {
	s.Organizer = val
}

// SetOccurrences sets the value of Occurrences.
func (s *PublicEventDetail) SetOccurrences(val []PublicOccurrence) {
	s.Occurrences = val
}

func (*PublicEventDetail) getPublicEventRes() {}

type PublicEventList []PublicEvent

func (*PublicEventList) listPublicEventsRes()         {}
func (*PublicEventList) listPublicFeaturedEventsRes() {}
func (*PublicEventList) listPublicRelatedEventsRes()  {}
func (*PublicEventList) listPublicUpcomingEventsRes() {}

// Ref: #/components/schemas/PublicOccurrence
type PublicOccurrence struct {
	ID                 UUID             `json:"id"`
	Name               string           `json:"name"`
	StartTime          time.Time        `json:"startTime"`
	EndTime            time.Time        `json:"endTime"`
	VenueName          string           `json:"venueName"`
	VenueAddress       string           `json:"venueAddress"`
	Status             OccurrenceStatus `json:"status"`
	WaitingRoomEnabled bool             `json:"waitingRoomEnabled"`
}

// GetID returns the value of ID.
func (s *PublicOccurrence) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *PublicOccurrence) GetName() string {
	return s.Name
}

// GetStartTime returns the value of StartTime.
func (s *PublicOccurrence) GetStartTime() time.Time {
	return s.StartTime
}

// GetEndTime returns the value of EndTime.
func (s *PublicOccurrence) GetEndTime() time.Time {
	return s.EndTime
}

// GetVenueName returns the value of VenueName.
func (s *PublicOccurrence) GetVenueName() string {
	return s.VenueName
}

// GetVenueAddress returns the value of VenueAddress.
func (s *PublicOccurrence) GetVenueAddress() string {
	return s.VenueAddress
}

// GetStatus returns the value of Status.
func (s *PublicOccurrence) GetStatus() OccurrenceStatus {
	return s.Status
}

// GetWaitingRoomEnabled returns the value of WaitingRoomEnabled.
func (s *PublicOccurrence) GetWaitingRoomEnabled() bool {
	return s.WaitingRoomEnabled
}

// SetID sets the value of ID.
func (s *PublicOccurrence) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PublicOccurrence) SetName(val string) {
	s.Name = val
}

// SetStartTime sets the value of StartTime.
func (s *PublicOccurrence) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetEndTime sets the value of EndTime.
func (s *PublicOccurrence) SetEndTime(val time.Time) {
	s.EndTime = val
}

// SetVenueName sets the value of VenueName.
func (s *PublicOccurrence) SetVenueName(val string) {
	s.VenueName = val
}

// SetVenueAddress sets the value of VenueAddress.
func (s *PublicOccurrence) SetVenueAddress(val string) {
	s.VenueAddress = val
}

// SetStatus sets the value of Status.
func (s *PublicOccurrence) SetStatus(val OccurrenceStatus) {
	s.Status = val
}

// SetWaitingRoomEnabled sets the value of WaitingRoomEnabled.
func (s *PublicOccurrence) SetWaitingRoomEnabled(val bool) {
	s.WaitingRoomEnabled = val
}

type PublicOccurrenceList []PublicOccurrence

func (*PublicOccurrenceList) listPublicEventOccurrencesRes() {}

// Ref: #/components/schemas/PublicOrganizer
type PublicOrganizer struct {
	ID            UUID                         `json:"id"`
	Slug          Slug                         `json:"slug"`
	Name          string                       `json:"name"`
	Logo          string                       `json:"logo"`
	Description   string                       `json:"description"`
	PublicContact PublicOrganizerPublicContact `json:"publicContact"`
}

// GetID returns the value of ID.
func (s *PublicOrganizer) GetID() UUID {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s *PublicOrganizer) GetSlug() Slug {
	return s.Slug
}

// GetName returns the value of Name.
func (s *PublicOrganizer) GetName() string {
	return s.Name
}

// GetLogo returns the value of Logo.
func (s *PublicOrganizer) GetLogo() string {
	return s.Logo
}

// GetDescription returns the value of Description.
func (s *PublicOrganizer) GetDescription() string {
	return s.Description
}

// GetPublicContact returns the value of PublicContact.
func (s *PublicOrganizer) GetPublicContact() PublicOrganizerPublicContact {
	return s.PublicContact
}

// SetID sets the value of ID.
func (s *PublicOrganizer) SetID(val UUID) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *PublicOrganizer) SetSlug(val Slug) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *PublicOrganizer) SetName(val string) {
	s.Name = val
}

// SetLogo sets the value of Logo.
func (s *PublicOrganizer) SetLogo(val string) {
	s.Logo = val
}

// SetDescription sets the value of Description.
func (s *PublicOrganizer) SetDescription(val string) {
	s.Description = val
}

// SetPublicContact sets the value of PublicContact.
func (s *PublicOrganizer) SetPublicContact(val PublicOrganizerPublicContact) {
	s.PublicContact = val
}

func (*PublicOrganizer) getPublicOrganizerRes() {}

type PublicOrganizerList []PublicOrganizer

func (*PublicOrganizerList) listPublicOrganizersRes() {}

type PublicOrganizerPublicContact map[string]jx.Raw

func (s *PublicOrganizerPublicContact) init() PublicOrganizerPublicContact {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/PublicSalePhase
type PublicSalePhase struct {
	ID                UUID            `json:"id"`
	Name              string          `json:"name"`
	StartTime         time.Time       `json:"startTime"`
	EndTime           time.Time       `json:"endTime"`
	MaxBuyPerCustomer int             `json:"maxBuyPerCustomer"`
	Status            SalePhaseStatus `json:"status"`
}

// GetID returns the value of ID.
func (s *PublicSalePhase) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *PublicSalePhase) GetName() string {
	return s.Name
}

// GetStartTime returns the value of StartTime.
func (s *PublicSalePhase) GetStartTime() time.Time {
	return s.StartTime
}

// GetEndTime returns the value of EndTime.
func (s *PublicSalePhase) GetEndTime() time.Time {
	return s.EndTime
}

// GetMaxBuyPerCustomer returns the value of MaxBuyPerCustomer.
func (s *PublicSalePhase) GetMaxBuyPerCustomer() int {
	return s.MaxBuyPerCustomer
}

// GetStatus returns the value of Status.
func (s *PublicSalePhase) GetStatus() SalePhaseStatus {
	return s.Status
}

// SetID sets the value of ID.
func (s *PublicSalePhase) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PublicSalePhase) SetName(val string) {
	s.Name = val
}

// SetStartTime sets the value of StartTime.
func (s *PublicSalePhase) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetEndTime sets the value of EndTime.
func (s *PublicSalePhase) SetEndTime(val time.Time) {
	s.EndTime = val
}

// SetMaxBuyPerCustomer sets the value of MaxBuyPerCustomer.
func (s *PublicSalePhase) SetMaxBuyPerCustomer(val int) {
	s.MaxBuyPerCustomer = val
}

// SetStatus sets the value of Status.
func (s *PublicSalePhase) SetStatus(val SalePhaseStatus) {
	s.Status = val
}

type PublicSalePhaseList []PublicSalePhase

func (*PublicSalePhaseList) listPublicSalePhasesRes() {}

// Ref: #/components/schemas/PublicTicketCategory
type PublicTicketCategory struct {
	ID                UUID   `json:"id"`
	Name              string `json:"name"`
	Zone              string `json:"zone"`
	Price             int64  `json:"price"`
	MaxBuyPerCustomer int    `json:"maxBuyPerCustomer"`
}

// GetID returns the value of ID.
func (s *PublicTicketCategory) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *PublicTicketCategory) GetName() string {
	return s.Name
}

// GetZone returns the value of Zone.
func (s *PublicTicketCategory) GetZone() string {
	return s.Zone
}

// GetPrice returns the value of Price.
func (s *PublicTicketCategory) GetPrice() int64 {
	return s.Price
}

// GetMaxBuyPerCustomer returns the value of MaxBuyPerCustomer.
func (s *PublicTicketCategory) GetMaxBuyPerCustomer() int {
	return s.MaxBuyPerCustomer
}

// SetID sets the value of ID.
func (s *PublicTicketCategory) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PublicTicketCategory) SetName(val string) {
	s.Name = val
}

// SetZone sets the value of Zone.
func (s *PublicTicketCategory) SetZone(val string) {
	s.Zone = val
}

// SetPrice sets the value of Price.
func (s *PublicTicketCategory) SetPrice(val int64) {
	s.Price = val
}

// SetMaxBuyPerCustomer sets the value of MaxBuyPerCustomer.
func (s *PublicTicketCategory) SetMaxBuyPerCustomer(val int) {
	s.MaxBuyPerCustomer = val
}

type PublicTicketCategoryList []PublicTicketCategory

func (*PublicTicketCategoryList) listPublicTicketCategoriesRes() {}

type PublishOrgEventForbidden Error

func (*PublishOrgEventForbidden) publishOrgEventRes() {}

type PublishOrgEventNotFound Error

func (*PublishOrgEventNotFound) publishOrgEventRes() {}

type PublishOrgEventUnauthorized Error

func (*PublishOrgEventUnauthorized) publishOrgEventRes() {}

type RejectAdminOrganizerApplicationForbidden Error

func (*RejectAdminOrganizerApplicationForbidden) rejectAdminOrganizerApplicationRes() {}

type RejectAdminOrganizerApplicationNotFound Error

func (*RejectAdminOrganizerApplicationNotFound) rejectAdminOrganizerApplicationRes() {}

type RejectAdminOrganizerApplicationUnauthorized Error

func (*RejectAdminOrganizerApplicationUnauthorized) rejectAdminOrganizerApplicationRes() {}

type RequestChangesAdminOrganizerApplicationForbidden Error

func (*RequestChangesAdminOrganizerApplicationForbidden) requestChangesAdminOrganizerApplicationRes() {
}

type RequestChangesAdminOrganizerApplicationNotFound Error

func (*RequestChangesAdminOrganizerApplicationNotFound) requestChangesAdminOrganizerApplicationRes() {
}

type RequestChangesAdminOrganizerApplicationUnauthorized Error

func (*RequestChangesAdminOrganizerApplicationUnauthorized) requestChangesAdminOrganizerApplicationRes() {
}

type RescheduleOrgOccurrenceForbidden Error

func (*RescheduleOrgOccurrenceForbidden) rescheduleOrgOccurrenceRes() {}

type RescheduleOrgOccurrenceNotFound Error

func (*RescheduleOrgOccurrenceNotFound) rescheduleOrgOccurrenceRes() {}

type RescheduleOrgOccurrenceUnauthorized Error

func (*RescheduleOrgOccurrenceUnauthorized) rescheduleOrgOccurrenceRes() {}

type ResubmitMyOrganizerApplicationNotFound Error

func (*ResubmitMyOrganizerApplicationNotFound) resubmitMyOrganizerApplicationRes() {}

type ResubmitMyOrganizerApplicationUnauthorized Error

func (*ResubmitMyOrganizerApplicationUnauthorized) resubmitMyOrganizerApplicationRes() {}

// Ref: #/components/schemas/SalePhase
type SalePhase struct {
	ID                UUID            `json:"id"`
	Name              string          `json:"name"`
	StartTime         time.Time       `json:"startTime"`
	EndTime           time.Time       `json:"endTime"`
	MaxBuyPerCustomer int             `json:"maxBuyPerCustomer"`
	Status            SalePhaseStatus `json:"status"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *SalePhase) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *SalePhase) GetName() string {
	return s.Name
}

// GetStartTime returns the value of StartTime.
func (s *SalePhase) GetStartTime() time.Time {
	return s.StartTime
}

// GetEndTime returns the value of EndTime.
func (s *SalePhase) GetEndTime() time.Time {
	return s.EndTime
}

// GetMaxBuyPerCustomer returns the value of MaxBuyPerCustomer.
func (s *SalePhase) GetMaxBuyPerCustomer() int {
	return s.MaxBuyPerCustomer
}

// GetStatus returns the value of Status.
func (s *SalePhase) GetStatus() SalePhaseStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SalePhase) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SalePhase) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SalePhase) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SalePhase) SetName(val string) {
	s.Name = val
}

// SetStartTime sets the value of StartTime.
func (s *SalePhase) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetEndTime sets the value of EndTime.
func (s *SalePhase) SetEndTime(val time.Time) {
	s.EndTime = val
}

// SetMaxBuyPerCustomer sets the value of MaxBuyPerCustomer.
func (s *SalePhase) SetMaxBuyPerCustomer(val int) {
	s.MaxBuyPerCustomer = val
}

// SetStatus sets the value of Status.
func (s *SalePhase) SetStatus(val SalePhaseStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SalePhase) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SalePhase) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*SalePhase) cancelOrgSalePhaseRes()  {}
func (*SalePhase) createOrgSalePhaseRes()  {}
func (*SalePhase) endOrgSalePhaseRes()     {}
func (*SalePhase) getOrgSalePhaseRes()     {}
func (*SalePhase) startOrgSalePhaseRes()   {}
func (*SalePhase) suspendOrgSalePhaseRes() {}
func (*SalePhase) updateOrgSalePhaseRes()  {}

type SalePhaseList []SalePhase

func (*SalePhaseList) listOrgSalePhasesRes() {}

// Ref: #/components/schemas/SalePhaseStatus
type SalePhaseStatus string

const (
	SalePhaseStatusComingSoon SalePhaseStatus = "coming_soon"
	SalePhaseStatusOnSale     SalePhaseStatus = "on_sale"
	SalePhaseStatusSuspended  SalePhaseStatus = "suspended"
	SalePhaseStatusEnded      SalePhaseStatus = "ended"
	SalePhaseStatusCanceled   SalePhaseStatus = "canceled"
)

// AllValues returns all SalePhaseStatus values.
func (SalePhaseStatus) AllValues() []SalePhaseStatus {
	return []SalePhaseStatus{
		SalePhaseStatusComingSoon,
		SalePhaseStatusOnSale,
		SalePhaseStatusSuspended,
		SalePhaseStatusEnded,
		SalePhaseStatusCanceled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SalePhaseStatus) MarshalText() ([]byte, error) {
	switch s {
	case SalePhaseStatusComingSoon:
		return []byte(s), nil
	case SalePhaseStatusOnSale:
		return []byte(s), nil
	case SalePhaseStatusSuspended:
		return []byte(s), nil
	case SalePhaseStatusEnded:
		return []byte(s), nil
	case SalePhaseStatusCanceled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SalePhaseStatus) UnmarshalText(data []byte) error {
	switch SalePhaseStatus(data) {
	case SalePhaseStatusComingSoon:
		*s = SalePhaseStatusComingSoon
		return nil
	case SalePhaseStatusOnSale:
		*s = SalePhaseStatusOnSale
		return nil
	case SalePhaseStatusSuspended:
		*s = SalePhaseStatusSuspended
		return nil
	case SalePhaseStatusEnded:
		*s = SalePhaseStatusEnded
		return nil
	case SalePhaseStatusCanceled:
		*s = SalePhaseStatusCanceled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Slug string

type StartOrgSalePhaseForbidden Error

func (*StartOrgSalePhaseForbidden) startOrgSalePhaseRes() {}

type StartOrgSalePhaseNotFound Error

func (*StartOrgSalePhaseNotFound) startOrgSalePhaseRes() {}

type StartOrgSalePhaseUnauthorized Error

func (*StartOrgSalePhaseUnauthorized) startOrgSalePhaseRes() {}

type SuspendAdminOrganizerForbidden Error

func (*SuspendAdminOrganizerForbidden) suspendAdminOrganizerRes() {}

type SuspendAdminOrganizerNotFound Error

func (*SuspendAdminOrganizerNotFound) suspendAdminOrganizerRes() {}

type SuspendAdminOrganizerUnauthorized Error

func (*SuspendAdminOrganizerUnauthorized) suspendAdminOrganizerRes() {}

type SuspendOrgSalePhaseForbidden Error

func (*SuspendOrgSalePhaseForbidden) suspendOrgSalePhaseRes() {}

type SuspendOrgSalePhaseNotFound Error

func (*SuspendOrgSalePhaseNotFound) suspendOrgSalePhaseRes() {}

type SuspendOrgSalePhaseUnauthorized Error

func (*SuspendOrgSalePhaseUnauthorized) suspendOrgSalePhaseRes() {}

// Ref: #/components/schemas/TicketCategory
type TicketCategory struct {
	ID                UUID                   `json:"id"`
	Name              string                 `json:"name"`
	Zone              string                 `json:"zone"`
	Price             int64                  `json:"price"`
	Quantity          int                    `json:"quantity"`
	Priority          int                    `json:"priority"`
	Metadata          TicketCategoryMetadata `json:"metadata"`
	MaxBuyPerCustomer int                    `json:"maxBuyPerCustomer"`
	CreatedAt         time.Time              `json:"createdAt"`
	UpdatedAt         time.Time              `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *TicketCategory) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *TicketCategory) GetName() string {
	return s.Name
}

// GetZone returns the value of Zone.
func (s *TicketCategory) GetZone() string {
	return s.Zone
}

// GetPrice returns the value of Price.
func (s *TicketCategory) GetPrice() int64 {
	return s.Price
}

// GetQuantity returns the value of Quantity.
func (s *TicketCategory) GetQuantity() int {
	return s.Quantity
}

// GetPriority returns the value of Priority.
func (s *TicketCategory) GetPriority() int {
	return s.Priority
}

// GetMetadata returns the value of Metadata.
func (s *TicketCategory) GetMetadata() TicketCategoryMetadata {
	return s.Metadata
}

// GetMaxBuyPerCustomer returns the value of MaxBuyPerCustomer.
func (s *TicketCategory) GetMaxBuyPerCustomer() int {
	return s.MaxBuyPerCustomer
}

// GetCreatedAt returns the value of CreatedAt.
func (s *TicketCategory) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *TicketCategory) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *TicketCategory) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *TicketCategory) SetName(val string) {
	s.Name = val
}

// SetZone sets the value of Zone.
func (s *TicketCategory) SetZone(val string) {
	s.Zone = val
}

// SetPrice sets the value of Price.
func (s *TicketCategory) SetPrice(val int64) {
	s.Price = val
}

// SetQuantity sets the value of Quantity.
func (s *TicketCategory) SetQuantity(val int) {
	s.Quantity = val
}

// SetPriority sets the value of Priority.
func (s *TicketCategory) SetPriority(val int) {
	s.Priority = val
}

// SetMetadata sets the value of Metadata.
func (s *TicketCategory) SetMetadata(val TicketCategoryMetadata) {
	s.Metadata = val
}

// SetMaxBuyPerCustomer sets the value of MaxBuyPerCustomer.
func (s *TicketCategory) SetMaxBuyPerCustomer(val int) {
	s.MaxBuyPerCustomer = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *TicketCategory) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *TicketCategory) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*TicketCategory) createOrgTicketCategoryRes() {}
func (*TicketCategory) getOrgTicketCategoryRes()    {}
func (*TicketCategory) updateOrgTicketCategoryRes() {}

type TicketCategoryList []TicketCategory

func (*TicketCategoryList) listOrgTicketCategoriesRes() {}

type TicketCategoryMetadata map[string]jx.Raw

func (s *TicketCategoryMetadata) init() TicketCategoryMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/TicketStatus
type TicketStatus string

const (
	TicketStatusReserved  TicketStatus = "reserved"
	TicketStatusValid     TicketStatus = "valid"
	TicketStatusCheckedIn TicketStatus = "checked_in"
	TicketStatusVoided    TicketStatus = "voided"
	TicketStatusRefunded  TicketStatus = "refunded"
)

// AllValues returns all TicketStatus values.
func (TicketStatus) AllValues() []TicketStatus {
	return []TicketStatus{
		TicketStatusReserved,
		TicketStatusValid,
		TicketStatusCheckedIn,
		TicketStatusVoided,
		TicketStatusRefunded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TicketStatus) MarshalText() ([]byte, error) {
	switch s {
	case TicketStatusReserved:
		return []byte(s), nil
	case TicketStatusValid:
		return []byte(s), nil
	case TicketStatusCheckedIn:
		return []byte(s), nil
	case TicketStatusVoided:
		return []byte(s), nil
	case TicketStatusRefunded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TicketStatus) UnmarshalText(data []byte) error {
	switch TicketStatus(data) {
	case TicketStatusReserved:
		*s = TicketStatusReserved
		return nil
	case TicketStatusValid:
		*s = TicketStatusValid
		return nil
	case TicketStatusCheckedIn:
		*s = TicketStatusCheckedIn
		return nil
	case TicketStatusVoided:
		*s = TicketStatusVoided
		return nil
	case TicketStatusRefunded:
		*s = TicketStatusRefunded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UUID uuid.UUID

type UpdateAdminCategoryBadRequest Error

func (*UpdateAdminCategoryBadRequest) updateAdminCategoryRes() {}

type UpdateAdminCategoryForbidden Error

func (*UpdateAdminCategoryForbidden) updateAdminCategoryRes() {}

type UpdateAdminCategoryNotFound Error

func (*UpdateAdminCategoryNotFound) updateAdminCategoryRes() {}

type UpdateAdminCategoryUnauthorized Error

func (*UpdateAdminCategoryUnauthorized) updateAdminCategoryRes() {}

type UpdateAdminCityBadRequest Error

func (*UpdateAdminCityBadRequest) updateAdminCityRes() {}

type UpdateAdminCityForbidden Error

func (*UpdateAdminCityForbidden) updateAdminCityRes() {}

type UpdateAdminCityNotFound Error

func (*UpdateAdminCityNotFound) updateAdminCityRes() {}

type UpdateAdminCityUnauthorized Error

func (*UpdateAdminCityUnauthorized) updateAdminCityRes() {}

type UpdateMyOrganizerApplicationBadRequest Error

func (*UpdateMyOrganizerApplicationBadRequest) updateMyOrganizerApplicationRes() {}

type UpdateMyOrganizerApplicationNotFound Error

func (*UpdateMyOrganizerApplicationNotFound) updateMyOrganizerApplicationRes() {}

type UpdateMyOrganizerApplicationUnauthorized Error

func (*UpdateMyOrganizerApplicationUnauthorized) updateMyOrganizerApplicationRes() {}

type UpdateOrgEventBadRequest Error

func (*UpdateOrgEventBadRequest) updateOrgEventRes() {}

type UpdateOrgEventForbidden Error

func (*UpdateOrgEventForbidden) updateOrgEventRes() {}

type UpdateOrgEventNotFound Error

func (*UpdateOrgEventNotFound) updateOrgEventRes() {}

type UpdateOrgEventUnauthorized Error

func (*UpdateOrgEventUnauthorized) updateOrgEventRes() {}

type UpdateOrgOccurrenceBadRequest Error

func (*UpdateOrgOccurrenceBadRequest) updateOrgOccurrenceRes() {}

type UpdateOrgOccurrenceForbidden Error

func (*UpdateOrgOccurrenceForbidden) updateOrgOccurrenceRes() {}

type UpdateOrgOccurrenceNotFound Error

func (*UpdateOrgOccurrenceNotFound) updateOrgOccurrenceRes() {}

type UpdateOrgOccurrenceUnauthorized Error

func (*UpdateOrgOccurrenceUnauthorized) updateOrgOccurrenceRes() {}

type UpdateOrgSalePhaseBadRequest Error

func (*UpdateOrgSalePhaseBadRequest) updateOrgSalePhaseRes() {}

type UpdateOrgSalePhaseForbidden Error

func (*UpdateOrgSalePhaseForbidden) updateOrgSalePhaseRes() {}

type UpdateOrgSalePhaseNotFound Error

func (*UpdateOrgSalePhaseNotFound) updateOrgSalePhaseRes() {}

type UpdateOrgSalePhaseUnauthorized Error

func (*UpdateOrgSalePhaseUnauthorized) updateOrgSalePhaseRes() {}

type UpdateOrgTicketCategoryBadRequest Error

func (*UpdateOrgTicketCategoryBadRequest) updateOrgTicketCategoryRes() {}

type UpdateOrgTicketCategoryForbidden Error

func (*UpdateOrgTicketCategoryForbidden) updateOrgTicketCategoryRes() {}

type UpdateOrgTicketCategoryNotFound Error

func (*UpdateOrgTicketCategoryNotFound) updateOrgTicketCategoryRes() {}

type UpdateOrgTicketCategoryUnauthorized Error

func (*UpdateOrgTicketCategoryUnauthorized) updateOrgTicketCategoryRes() {}
